### ISSUE TITLE
How to make a version ?

### ISSUE THREAD

**Issue by feugy** [OptiKey/OptiKey#184]
The [Deployment file](https://github.com/OptiKey/OptiKey/blob/master/docs/Deployment.txt) mentioned two script (script 1 and script 3), but I did not found them in sources.

Is it possible to commit them ? Or the update the documentation ?

**Comment by JuliusSweetland** [comment]
Hi, I'm afraid all the deployment stuff is local to my machine at the moment as you have to sign the assemblies and the certificate is assigned to me personally, rather than to OptiKey as an organisation. I'm slowly moving towards opening OptiKey fully (hence the new OptiKey organisation I invited you to), at which point I'll release all the deployment scripts.

**Comment by feugy** [comment]
Fine !

**Comment by alexandre-mbm** [comment]
Today, November 2016, what I will need and still is not published? Where are these scripts?

Which is the toolchain?
Some Microsoft Visual Studio Community or Express will work?

**Comment by alexandre-mbm** [comment]
I'm impressed! It was very easy to deploy the Microsoft's toolchain and build and execute branches. Basically:

1. Install Microsoft Visual Studio Community 2015
2. Clone the Git repository by using the "https" URL
3. Do checkout for the branch of interest
4. Open Solution
5. Build All or Start

Amazing!
