### ISSUE TITLE
Allow input from mouse *and* eye tracker

### ISSUE THREAD

**Issue by kirstymcnaught** [OptiKey/OptiKey#228]
There are many times when it would be really useful to control OptiKey with a mouse, even when your main control is with an eye tracker. Most commonly you might be set up to use an eye tracker, when the eye tracker disconnects itself or otherwise isn't working. You want to cleanly close OptiKey with the mouse, or maybe show a new user what the different pages contain, or access the 'recalibrate eye tracker' option in OptiKey.

**Comment by JuliusSweetland** [comment]
I agree. There is complexity where the user is using an eye tracker to simulate mouse movement and moves the cursor over OptiKey.

Initial thoughts are that the easiest way to achieve this would be to have the point source "fall back" to the mouse where the eye tracking input is lost/stale/not useful. This would cover scenarios where the eye tracker fails/is disconnected. It would also allow you to use the mouse by forcing OptiKey to "fall back" to the mouse by covering the tracker's camera, or moving out of the track box.

I think a notification would be useful when falling back to mouse, or resuming eye control.

Does that sound suitable?

**Comment by kirstymcnaught** [comment]
Yes, that sounds like a good solution.

**Comment by JuliusSweetland** [comment]
@kirstymcnaught I'll add this to my roadmap and get to it in due course.

**Comment by JuliusSweetland** [comment]
Further thoughts:

Option 1: Fall back to mouse when eye tracking signal is lost (for x amount of time) AND THEN when the mouse next moves (otherwise any time the eyes are lost the current, static cursor position may be incorrectly used to make selections).

Option 2: Modify OptiKey so that point sources and trigger sources can be switched without a restart. Add shortcut(s) to switch to/from mouse as a source.

**Comment by yahnatan** [comment]
This feature will be really helpful when using Optikey for its "magnetic cursor" mode in order to use an eyegaze camera with other applications in a free / open source way. My typical use case (with my son) involves turning on Optikey, enabling the magnetic cursor feature, and then minimizing Optikey. Typically I do this using my eyes and then switch user profiles to my son once Optikey is minimized. It would be faster if I could do it with a mouse.

It would be even faster if I could do it using the tablet's touchscreen itself. I thought there was an issue to add support for clicks on the touch screen but looked and couldn't find it. Is that related to this feature at all?

**Comment by JuliusSweetland** [comment]
@yahnatan Touch support is not part of this piece of work, but it is on my todo list. I'll find/recreate a ticket for it now.

**Comment by mostlyjason** [comment]
This would be useful to me since I find the head mouse more accurate for fine movements like typing and I use my eye tracker for large movements like quickly warping across the screen. It's hard to use the mouse with optikey since it changes mouse focus. It'd be nice if it works like the windows on screen keyboard and keeps focus on the target app unless you click on the window header or task bar.

**Comment by JuliusSweetland** [comment]
Manual/mouse mode added in v.2.3.13. For now it is fairly basic; available on the right click context menu, or by pressing ALT+ENTER with OptiKey focussed, this will toggle between whichever input method you are using (e.g. an eye tracker) and mouse control, allowing a carer to easily take temporary control and then switch back to eye tracking.

**Comment by alexandre-mbm** [comment]
- [ ] Hint: checkbox at config to do this being minus easy for a sake of security
