### ISSUE TITLE
Error message when I try to download Optikey

### ISSUE THREAD

**Issue by MikePG7** [OptiKey/OptiKey#236]
Hi Julius - When I try to download on my new laptop I get this message: "The signature of OptiKeySetup-2.3.0 (2).exe is corrupt or invalid"
Please let me know how to proceed. 
Cheers.

**Comment by JuliusSweetland** [comment]
@MikePG7 Thanks for reporting the problem. I believe the issue is that Microsoft no longer support the hash function used in my code signing certificate. I have re-issued and resigned the release. Could you please try downloading and trying again?

I'm not 100% sure my fix will work as the signed installer is not currently verifying, but please give it a go and let me know what happens for you.

**Comment by MikePG7** [comment]
Thanks Julius - that worked (although I got a couple of 'are you sure?' messages on the screen - see attached screenshots).I may need your advice on calibrating the eye tracker in a day or two - is that ok?Michael.

Date: Fri, 4 Mar 2016 14:27:13 -0800

**Comment by JuliusSweetland** [comment]
Good stuff. Yeah no problem. Email me direct on optikeyfeedback@gmail.com

**Comment by JuliusSweetland** [comment]
Oh, and the warnings were probably along the lines of a warning that not
enough people download the setup file to be confident that it's safe.
Basically it doesn't have enough "reputation" with Microsoft yet. That will
build up over time. Let me know if the message was something else.
