### ISSUE TITLE
Localisation: Polish

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#238]
**1.Transifex translation of UI strings:** currently 100%

**2.Keyboard layout:**
None yet

**3.Alphabet:**
a)Letters: ? individual letters

b)Diacritics that can be added to individual letters (these will be dead keys): ?

Total: ? keys

**4.Word list:** None yet

**5.Branch:** None yet

**Comment by lukeses** [comment]
@H1ghty @JuliusSweetland Most of the work is done, but I haven't make a pull request with Polish version yet.
My family member is using Polish version as daily basis. I need to merge with changes from the newest release that was made few weeks ago. Probably there will be not so much to do to merge with newest version.
2. I prepare version with the most popular diacritics on main keyboard. It was really helpful for my uncle using OptiKey.
3. I will show you screenshot with current version tomorrow.
4. I found quite good database with most popular Polish words. It consists of ca. 70 000 words. As I tested it is enough to use word prediction.

For sure, @H1ghty it would be great, if you could test Polish version and check if we can make any improvements in Polish version.

**Comment by H1ghty** [comment]
hi @lukeses Thanks for info. I can test it. That would be great!

**Comment by JuliusSweetland** [comment]
@lukeses that's excellent news. Looking forward to seeing a screenshot.
I'll then create an issue and a branch for Polish.

**Comment by lukeses** [comment]
@H1ghty @JuliusSweetland Here is Polish version that need to be updated: https://github.com/lukeses/OptiKey/tree/Polish
As you see I need to make a big update.
For now Polish version looks like this
![keyboard polish](https://cloud.githubusercontent.com/assets/4325715/14153365/e393471a-f6b7-11e5-820d-7fe286767a4c.PNG)
![diacritics](https://cloud.githubusercontent.com/assets/4325715/14153493/4e668336-f6b8-11e5-84e6-435d5604dd02.PNG)

We must think about position of diacritics because I know that my uncle would like to have dicritics on first screen. Probably other Polish people would agree that we use diacritics quite often. For sure it can't look like on screens above. There is a disorder now because I made this fixes quickly and we need to repair this.

**Comment by JuliusSweetland** [comment]
@lukeses I've just had a quick look over all of this (including your code) and it looks great - nice work!

I haven't merged the changed back into master yet, but on the Greek branch (which is being finalised for release at the moment) I have changed a couple of things... Primarily, all diacritic keyboards are the same for all languages. This is because of the second main change, which is the introduction of diacritic "dead" keys, which work by first pressing the diacritic (or diacritics) that you want to add to a character, followed by the character. This screenshot is in Greek (as I was just discussing this on another issue), but I've added arrows to 2 diacritic dead keys so you can see what I'm talking about:
![image](https://cloud.githubusercontent.com/assets/4722561/14154461/75341360-f6b4-11e5-94b3-3eb28317ded6.png)

These keys mean that we can reduce the number of keys on the main Alpha keyboard if a diacritic is shared across a few letters. ALTHOUGHT, I've just had a skim read of this https://en.wikipedia.org/wiki/Polish_alphabet and it looks like these decorated letters are stand alone characters of their own, so ignore what I just said!

Anyway, it looks good. We just need to discuss things like;

1. Whether decorated letters are 1st class citizens and deserve to be their own keys on the Alpha keyboard, or whether we should use diacritic dead keys.

2. We need a bit more info in the top post above, e.g. which keyboard layout we should use. See this page for 2 polish layout options: http://ascii-table.com/keyboards.php. This page also has 2 options: http://kbd-intl.narod.ru/english/layouts

3. We need a word list. There are a load here: https://invokeit.wordpress.com/frequency-word-lists/ which are taken from film and tv scripts. I can extract the top 100k (for example) most common words and use this, unless you have a better list?

**Comment by H1ghty** [comment]
Hi,
@lukeses  wow, nice job! thank you very much. I would like to install it for my mother, unfortunately she also has ALS. But we will be able to give an input how it works.


@JuliusSweetland I got a question, is somewhere here an instruction how to hmm  build this project with polish language? Because i'm not familiar with c# technologies, so I don't really know how to use it with different language ;)


btw.
For now we are using http://www.click2speak.net/ , but it doesn't work that stable like optikey. 
Also with some help ACAT is translated a bit https://github.com/01org/acat/issues/7

**Comment by JuliusSweetland** [comment]
@H1ghty To build the project you need visual studio. There is a free version available called Visual Studio Community. However, perhaps @lukeses can build you a version for initial testing? I will release an official version of OptiKey with Polish in due course, but there is a bit of work to be done first.

RE: ACAT - it's interesting to see how localisation is being attempted within the ACAT project - great to see!

Out of interest what do you mean when you say that Click2Speak is not stable?

**Comment by lukeses** [comment]
I played with merging with newest master. Some changes was needed in Polish xamls but now it builds. :) It isn't pushed yet because I would like to update file with translation of GUI.

1. and 2. I think that all letters should be visible on keyboard. As I saw it was easier for my uncle to have all letters.

Based on your proposals, some kind of standards and my sources (https://pl.wikipedia.org/wiki/Klawiatura_maszynistki#/media/File:KB_Polish_QWERTZ_PN87_commons.svg, https://pl.wikipedia.org/wiki/Klawiatura_maszynistki#/media/File:KB_Polish_QWERTZ_PN87_Mac_svg.png)
I have think about this layout:
![polish alpha](https://cloud.githubusercontent.com/assets/4325715/14158888/fa9897ce-f6d2-11e5-9579-e48e299254d3.PNG)

If it will be good I will need to prepare only conversation layout in similar way.

3. @JuliusSweetland word list was one of the hardest thing. :) As you can see Polish version is added to my fork: https://github.com/lukeses/OptiKey/tree/Polish/src/JuliusSweetland.OptiKey/Dictionaries

4. @H1ghty I will prepare a build and upload it.

@H1ghty Do you have any eye tracker? If you would like to test the eye tracker, we can meet because I live in the same city as you in Poznań (I have just read that from your Github profile).

**Comment by JuliusSweetland** [comment]
@lukeses I can't comment on how suitable the layout is to use, but it looks good to me. The only change I can think of is that I have made a small change to the Alpha keyboard of all languages - nothing major, but I've changed the keys on the right of the keyboard a bit (in the Greek branch which will be merged into master soon). You might want to manually make this change as well:
![image](https://cloud.githubusercontent.com/assets/4722561/14154461/75341360-f6b4-11e5-94b3-3eb28317ded6.png)

Yes, a ConversationAlpha will be needed.

Your word list looks good @ 64k - nice work. This is often the hardest thing to get right.

Lastly, you have a random "TextFile1.txt" in your dictionaries directory. I think this should be removed before you create a pull request. Speaking of a PR - let me know once you guys are happy with everything and I will create a Polish branch for you to create the PR against.

**Comment by H1ghty** [comment]
@lukeses  Thanks. That will be grat if you can upload it for me. 
About Eye tracker , we got tobii camera but for now we are using http://www.cameramouse.org/ which is easier for my mother to use.

about the meeting, we can consider it and share our experience about such software :) 
Now I'm looking for very sensitive sensor or something to replace left mouse click, I think that I saw that in SystemSensor or something like that.

**Comment by lukeses** [comment]
@H1ghty Here is a working version of Optikey with Polish:
https://www.dropbox.com/s/j4lwpmgu8mech12/Release.zip?dl=0

I will work on finisihing our language to make it ready for PR.

**Comment by PiotrKurnik** [comment]
Fantastic job! I saw that Polish was missing and decided that I have to crack down on it. Your help is much appreciated!

**Comment by KrzysztofGoralski** [comment]
HI @lukeses thank you. We were testing for some time. We think it is very nice. Really good job. And polish chars on the first 'page' is quite nice idea

@JuliusSweetland  about not stable click2speak. Floating windows, they move around, sometimes don't really know why. I like that OptiKey is solid, keyboard doesn't window itself etc.Sometimes it is also quite slow.

What we like about click2speak is prediction. It helps a lot because it can predict the whole sentence , not just the single word.

**Comment by andylamp** [comment]
@KrzysztofGoralski All are valid points. We are seeking to address them... I think the priority is as follows:

* Performance: Generally speaking, as it stands OptiKey cannot handle large dictionaries very efficiently this will be address soon (hopefully) as work on that will start after the current beta branch is released.

* Prediction: Let me be clear we *cannot beat swiftkey*; swiftkey is a big product and has some awesome prediction features as well as some stellar personalization. This is where we lack, not only currently but also for the future -- if we want to support non-latin based languages properly. This is a big and complex task so unfortunately will take sometime to be addressed.

As a final word please remember that @JuliusSweetland is mostly doing one-man job... we try to help... but the hours he puts are quite a bit more than most of us (if not all).

**Comment by KrzysztofGoralski** [comment]
Hi @andylamp Ofcourse I understand. @JuliusSweetland  made amazing job. 
I just wanted to give some input. It is really great that such tools are available for free. That really helps people.

**Comment by JuliusSweetland** [comment]
@KrzysztofGoralski @andylamp thanks for your input and feedback.

**Comment by JuliusSweetland** [comment]
@lukeses @KrzysztofGoralski I have created a Polish branch here: https://github.com/OptiKey/OptiKey/tree/Polish

Perhaps you could integrate your work to get Polish working and create a pull request? Be aware that there is no longer a requirement to customise the Diacritic keyboards, and OptiKey now has the concept of "dead key" diacritics, where you can press the diacritic key (e.g. an acute accent) followed by the relevant letter. Check out any of the existing languages to see how this works, or ask me.

**Comment by JuliusSweetland** [comment]
@lukeses @KrzysztofGoralski If you are happy with your testing shall we look at merging Polish into the main OptiKey repo for a release?

**Comment by Noga2** [comment]
Thanks for the good job. My brother thanks to this program is a standalone.

Is it possible to lock the left mouse button. To work Like button for zooming? Each selection again left mouse button is tiring.

This is an option from the "Windows Control" Tobii DYNAVOX. but we have only Tobii EyeX.

**Comment by JuliusSweetland** [comment]
Hi Noda. If you go to the mouse keyboard and then expand it to show the
full set of mouse operations there is a key called "left down/up" which
presses and hold down the left mouse button until it is selected again to
release it. Is this what you mean?

**Comment by Noga2** [comment]
We are really grateful for the polish version of the program. it works well for my brother, who was born with cerebral palsy, and your program is the only way for my brother to be independent.

Although I have a small question: is it possible to lock the left mouse button? It would be wonderful if it worked as a zooming button. It is really tiring for him to press each time the button again and again.

This is an option from the "Windows Control" Tobii DYNAVOX. but we have only Tobii EyeX.

**Comment by JuliusSweetland** [comment]
That's great feedback! I've replied to your other post asking this question.

**Comment by JuliusSweetland** [comment]
@lukeses Are you happy for me to merge in the polish branch and create an official release?

**Comment by Noga2** [comment]
I did not expect such a quick response so I edited my last  question.

Maybe the Polish version does not have this option?

**Comment by JuliusSweetland** [comment]
I can't test right now, but it should do. Go to the menu and then mouse.
There's a key to expand the keyboard to show all the mouse keys (it expands
from a single row of keys to a full keyboard of 4 or 5 rows). Left down/up
should then be available.

**Comment by Noga2** [comment]
It is not about to lock button just kind of loops by selecting the left mouse button.

**Comment by JuliusSweetland** [comment]
Can you talk me through what you are trying to do and how you would like
OptiKey to work?

**Comment by Noga2** [comment]
I need button to work  like "LEFT..." button in this video.
https://www.youtube.com/watch?v=rqcN9IZ39_4&feature=youtu.be

**Comment by JuliusSweetland** [comment]
Ah I see. Yes this is possible. I'll try to find some time to add this
functionality soon.

**Comment by alexandre-mbm** [comment]
This strategy for pointer by using transparency appears to be very good! Or the programmer is very skilled?! Or both?

**Comment by Noga2** [comment]
BKB (https://github.com/MastaLomaster/bkb) is the first program that my brother tested.

With Tobii EyeX worked well ..
But it have a limited possibility.

My brother starts to learn words, learn to spell. So your program with the Polish version is great. The only thing missing is the magic button that works until you turn it off.

Thanks for the quick reply.
We look forward to the new functionality and good luck!

**Comment by lukeses** [comment]
@JuliusSweetland I see more and more people try to use Polish version. During next 2 weeks I will try to merge my branch with your master branch.

**Comment by JuliusSweetland** [comment]
@lukeses No rush, but let me know when you've created a pull request and I will release it.

**Comment by Noga2** [comment]
When can I expect an additional option?

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
