### ISSUE TITLE
Making an app fullscreen breaks OptiKey position/size

### ISSUE THREAD

**Issue by kirstymcnaught** [OptiKey/OptiKey#251]
I realise that it doesn't make sense to have a full screen app *and* expect to use OptiKey on top, but if you accidentally set Minecraft to full screen the results are weird and it's hard to escape from the situation. 

Using OptiKey release 2.3.0.

1) Dock OptiKey 
2) Launch Minecraft
3) Set Minecraft to be fullscreen
   - Minecraft takes up the whole screen, without OptiKey, as expected.

then:
4) Immediately set Minecraft to be not-fullscreen.
  - OptiKey ends up snapping to the wrong part of the screen, has to be fixed with a restart or re-docking from size/position

or:
4) Try to click other buttons in the full-screen Minecraft.
  - OptiKey keeps stealing focus and it's impossible to reset Minecraft to be not-fullscreen without redocking or quitting OptiKey first.

**Comment by kirstymcnaught** [comment]
Video demo here:
https://youtu.be/SLKeAP5uRvQ

**Comment by JuliusSweetland** [comment]
I suspect this issue is due to fullscreen Minecraft changing the screen resolution. Currently there is nothing in OptiKey to detect a change like this, but Windows will force a resize on OptiKey if it would be too large for the new screen size. Once Minecraft is returned to a windowed mode, or closed, OptiKey will be left in an odd state as the resolution will be reset, but OptiKey won't be aware of that change. 

Can you let me know what happens if you then attempt to jump a docked OptiKey (or jump and then dock a floating OptiKey) to a screen edge after exiting from fullscreen Minecraft? Does this solve the problem?

**Comment by JuliusSweetland** [comment]
@kirstymcnaught Also, nothing to do with this issue, but I've considered your suggestion of making OptiKey auto dock when you use the jump keys if it is floating. I'm not sure I want to make that change - I understand that the current model requires you to remember to move OptiKey over the edge, but I like the explicit action to take it out of floating mode, rather than just forcible dock it. If I changed it then the diagonal jump keys would be come meaningless and the whole change doesn't feel like a good one to me. Happy to reconsider if you'd like to discuss further though.

**Comment by kirstymcnaught** [comment]
Okay, that makes sense. If I remember correctly, once you've closed Minecraft, you have to undock and then re-dock before OptiKey is happy again.

**Comment by kirstymcnaught** [comment]
@JuliusSweetland On the floating vs docking transition, I think it's totally reasonable to have an explicit extra step to go from at-the-edge-but-floating to docked-at-the-edge. The only problem is it's not clear what that action should be. What I'd really like is an explicit 'set-docked/set-floating' action, so that the state is fully observable and controllable. But if that doesn't fit in, maybe at least jumping to an edge when you're already there should dock the keyboard, in the same way that the final 'move' action does? I suspect that if that had been the case, I would have discovered it by accident and not started getting confused.

**Comment by JuliusSweetland** [comment]
That's a good idea. I'll add that.
