### ISSUE TITLE
Localisation module review

### ISSUE THREAD

**Issue by ilanMatityahoo** [OptiKey/OptiKey#269]
Dear Julius,

We are students for M.Sc,
In our project we chose to model the OptiKey, we created an activity diagram for the Localisation module.

Attached is the link to the activity diagram:
https://github.com/adirel/ASOSMA/blob/master/OptiKey/images/ActivityDiagram.png

Could you please review it for us?

Thank you in advance
Ilan Matityahoo

**Comment by JuliusSweetland** [comment]
@ilanMatityahoo great work. There's one step missing, only because it was missing from the localisation document and I've not pushed my update yet. The missing step involves adding a new case to the switch statement in MainViewModel subscription handler class to react to the selection of a new language key, e.g. When adding German you'd need a case for the function key GermanGermany which would switch the keyboard language to German.

**Comment by JuliusSweetland** [comment]
Two more things: 

1. You need to add new cases to the keyboard host class to know how to change to the new alpha and conversation alpha keyboards. This should be very very last step.

2. the last two steps could be "add a new alpha keyboard" and "add a new conversion alpha keyboard"?

**Comment by katyadenef** [comment]
Thanks a lot for your comments, Julius.
We will add the proposed chanes.

BR,
Katya.

**Comment by JuliusSweetland** [comment]
No problem. I'll close this issue in the mean time.

**Comment by Doneykkk** [comment]
nice job~

**Comment by alexandre-mbm** [comment]
**This is awesome!** It is all that I was needing to working.

![Activity Diagram for the Localisation module](https://raw.githubusercontent.com/adirel/ASOSMA/master/OptiKey/images/ActivityDiagram.png)
