### ISSUE TITLE
Localisation: Slovak

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#281]
**1.Transifex translation of UI strings:** Incomplete

**2.Keyboard layout:**  http://ascii-table.com/keyboard.php/245
![image](https://cloud.githubusercontent.com/assets/4722561/19223152/658718ba-8e60-11e6-9aa0-7a6a3bc40947.png)

**3.Alphabet:**
a)Letters: https://en.wikipedia.org/wiki/Slovak_orthography
A a
Á á
Ä ä
B b
C c
Č č
D d
Ď ď
DZ dz
DŽ dž
E e
É é
F f
G g
H h
CH ch
I i
Í í
J j
K k
L l
Ĺ ĺ
Ľ ľ
M m
N n
Ň ň
O o
Ó ó
Ô ô
P p
Q q
R r
Ŕ ŕ
S s
Š š
T t
Ť ť
U u
Ú ú
V v
W w
X x
Y y
Ý ý
Z z
Ž ž
The letters Q, W and X are only used in loanwords.

b)Diacritics that can be added to individual letters (these will be dead keys): 
The acute mark (in Slovak "dĺžeň", "prolongation mark" or "lengthener") indicates length (e.g. í = approximately [iː]). This mark may appear on any vowel except "ä" (wide "e", široké "e" in Slovak). It may also appear above the consonants "l" and "r", indicating the long [lː] and [rː] sounds.

The circumflex ("vokáň") exists only above the letter "o". It turns the o into a diphthong (see below).

The umlaut ("prehláska", "dve bodky" = two dots) is only used above the letter "a". It indicates a raised vowel, almost an "e", similar to German ä.

The caron (in Slovak "mäkčeň", "palatalization mark" or "softener") indicates a change of alveolar fricatives into either post-alveolar or palatal consonants, in informal Slovak linguistics often called just "palatalization". Eight consonants can bear a caron. Not all "normal" consonants have a "caroned" counterpart:

In printed texts, the caron is printed in two forms: (1) č, dž, š, ž, ň and (2) ľ, ď, ť (looking more like an apostrophe), but this is just a convention. In handwritten texts, it always appears in the first form.

c)Other keys: 

Total: X keys

**4.Word list:** None yet

**5.Anything else:** None yet

**BRANCH:** None yet

Similar Slovenian keyboard:
![image](https://cloud.githubusercontent.com/assets/4722561/19223086/bb6486b6-8e5e-11e6-9fc8-d9929dbd90e1.png)

**Comment by TheGreenAirplane** [comment]
I've looked at the Slovenian keyboard like you suggested. However, the Slovenian keyboard doesn't use dead keys. Instead all the special characters have their own key. This is relatively easy, since Slovenian only seems to have 5 special characters. Slovak has 17.
I did find an example of dead keys in the Spanish keyboard: It has a dead key for the acute accent ´, one for the diaeresis ¨ (umlaut) plus a separate key for the charecter ñ. This approach would work for Slovak. We'd need two dead keys and two separate keys for special characres. Here's the complete list:
´ - Acute accent:
A / a + ´ = Á / á
E / e + ´ = É / é
I / i + ´ = Í / í
L / l + ´ = Ĺ / ĺ
O / o + ´ = Ó / ó
R / r + ´ = Ŕ / ŕ
U / u + ´ = Ú / ú
Y / y + ´ = Ý / ý

ˇ - The caron:
C / c + ˇ = Č / č
D / d + ˇ = Ď / ď
L / l + ˇ = Ľ / ľ
N / n + ˇ = Ň / ň
S / s + ˇ = Š / š
T / t + ˇ = Ť / ť
Z / z + ˇ = Ž / ž

Other special characters:
 Ä / ä, Ô / ô

**Comment by TheGreenAirplane** [comment]
Here's a mockup of what the Slovak keyboard could look like. It's similar to Czech, except you need 4 extra characters instead of 3.
![Slovak keyboard proposal](https://cloud.githubusercontent.com/assets/12677130/19287096/aa43b43a-9000-11e6-8b0f-475897f6d5fc.png)
Just a small update, I expect to finish the Slovak translation on Transifex by Saturday evening. Then I'll continue with the other tasks.

**Comment by JuliusSweetland** [comment]
@TheGreenAirplane This mockup also looks good. Nice work.

**Comment by JuliusSweetland** [comment]
@TheGreenAirplane Hi. How are you getting on?

**Comment by TheGreenAirplane** [comment]
Hi Julius,

I just got back from a two-week vacation, so I haven't made any progress in
the past two weeks. However, before the vacation I've finished translating
the string resources to Slovak and started modifying the code according to
the guide. The only thing that's left to do from programming standpoint is
adding the keyboard layout. I'll do that as soon as I have some free time,
which I guess will be on Saturday.
As for Czech, I've passed the resource file to a relative before I left. I
haven't checked on their progress yet.
So Slovak could be ready by Sunday, assuming we're able to find a suitable
dictionary file, and Czech will be done whenever I get the translated
strings.

Robin

**Comment by JuliusSweetland** [comment]
Excellent, thanks Robin. No rush at do, just checking in.

**Comment by TheGreenAirplane** [comment]
**5.Anything else:**
Text-to-speech software. Microsoft doesn't seem to have released a Slovak voice for Windows, and trying to use the English voice to read Slovak is pointless. I have found one such software that's free for use:
[http://epos.ufe.cz/](http://epos.ufe.cz/)
You can download the latest verison here:
[http://epos.ufe.cz/download/bin/win32/EposSetup-2.4.85p.exe](http://epos.ufe.cz/download/bin/win32/EposSetup-2.4.85p.exe)
Once you've downloaded the file, install it. Then in OptiKey Management Console, you can select a voice under Sounds->Speech->Voice.
Several Czech voices are available, 
both male: machac, bob,
and female: violka
There is only one Slovak voice, igor, which is male. 
You can either stick with igor, or try one of the Czech voices. The pronunciation is similar enough, and the Czech voices are generally better quality. However, they can have problems with certain letters that are not present in Czech, such as ľ or ô, so you may want to avoid them when speaking. You'll also be speaking Slovak with a Czech accent.

**Comment by JuliusSweetland** [comment]
Merged. This will be released in 2.3.8
