### ISSUE TITLE
Localisation: Georgian

### ISSUE THREAD

**Issue by OneBadNinja** [OptiKey/OptiKey#331]
Hi Julius, to follow up on your previous directions:

> @OneBadNinja Hi, that sounds great. I have approved the language on Transifex. The localisation guide is here: https://github.com/OptiKey/OptiKey/blob/master/docs/Localize.md
> 
> Have a read and let me know if you have any questions. The main steps are:
> 
> 1.Complete a Transifex translation
> 2.Get a wordlist. 310,000 is probably a bit large, but potentially useable. We can test.
> 3.Identify the keyboard layout and build the keyboards
> 4.Solve any language specific problems, such as the lack of casing.

The following data is now available:

## Transifex Translation
All strings have now been translated and double-checked, so that's ready to go! Please let me know when you create the Georgian branch and approve the translation for the .resx file

## Word List
There are only two publicly available resources I have been able to get my hands on. The first contained 310,000 words (above the recommended 100k) and upon closer inspection also included antiquated words from historic literature.

Given that it would not be feasible to utilise or filter these, I found an alternative resource containing 40000 of the most used Georgian bigrams from Wikipedia. Splitting these and discarding duplicates, the result is a file containing approximately 30,000 Georgian words that appear to be valid. I believe we should go with this.

I have exported the word column from the database into a file with each word separated by a newline. I have renamed the extension to .dic - is this valid for OptiKey?

## Keyboard Layout

The Georgian alphabet contains 33 letters and no casing. There are two main keyboard layouts available (please ignore the standard symbols and other buttons - the letters would simply be tailored for the current layout in optikey):

### Layout 1
![Imgur](http://i.imgur.com/7YGND3K.png)
This layout replaces the 26 Latin letters on the keyboard with the additional 7 Georgian letters available via the shift key.

### Layout 2
![Imgur](http://i.imgur.com/CVLaBmQ.jpg)
This layout presents all 33 letters on the keyboard without the use of the shift key. I believe this would be the best method to use, as using shift to find the remaining 7 letters would be cumbersome and potentially confusing for elderly users. 

Hence, an additional 7 letters would be added to the default layout for the Georgian version. Does this seem feasible to you in terms of spacing? We could give it a try. Potentially even remove the shift key for Georgian as it would be redundant.

## Language Specific Problems
This is solely the lack of casing, no diacritics. I figured the simplest way would be to contain the same characters for both uppercase and lowercase modes of the program (if keyboard layout #2 is used for instance) thus avoiding additional restructuring. How does this sound to you?

I have not used visual basic before, but given my experience as a web developer I would like to give it a shot. I would also like to attempt translating the 'blocky keyboard' layout you have recently helped integrate into the program. I would appreciate any additional advice you might have along the way on how to proceed with this.

Thank you for your help!
Joey

**Comment by JuliusSweetland** [comment]
@OneBadNinja Hi. 

1.A new branch has been created here: https://github.com/OptiKey/OptiKey/tree/Georgian - I have added the resource from Transifex as Resources.ka-GE.resx

2.A 30,000 word list sounds good. I am of the opinion that less is better as with larger dictionaries OptiKey tends to suggest very similar, but incorrect words. We can refine this later if you think it is too small. Yes, a plain text file with extensions .dic is correct. Make sure this file is saved with UTF-8 encoding - you can do this in Notepad in the Save As dialog, for example:

![image](https://user-images.githubusercontent.com/4722561/28250714-56b465b6-6a67-11e7-8dd5-3e6143b82ebf.png)

3.I agree that all 33 keys should be displayed and the SHIFT key can be removed from both the Alpha and ConversationAlpha keyboards. Rather than specifying the same letter for each key as the ShiftUpText and ShiftDownText you can just set the Text property (make sure the Text and Value properties are set - don't worry about ShiftUpText and ShiftDownText).

4.OptiKey is written in C# rather than Visual Basic. The UI technology is called WPF.

I am available if you have any questions or get stuck - just check in and push wherever you are and I can pick it up and help. The Georgian branch doesn't always have to build before you commit and push your changes.

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.

**Comment by OneBadNinja** [comment]
Hi Julius, could you please re-open this? I would like to give it another shot. Thanks!

**Comment by JuliusSweetland** [comment]
@OneBadNinja done

**Comment by OneBadNinja** [comment]
> @OneBadNinja done

Thank you Julius! We have now updated the Georgian localisation on Transifex, could this please be reviewed and the Georgian branch created?

Thanks!

**Comment by OneBadNinja** [comment]
Thank you Julius! I can't seem to find an option for generating the .resx file, is this to be done by you? Cheers!

**Comment by JuliusSweetland** [comment]
Here you go (I downloaded the resource file from Transifex and zipped it up). You will need to extract the file and add it to the solution in the Properties directory.
[Resources.ka-GE.zip](https://github.com/OptiKey/OptiKey/files/2705488/Resources.ka-GE.zip)

**Comment by OneBadNinja** [comment]
Hi Julius! Apologies for taking my time, I've had to focus on exams. I have now completed Georgian localisation... it works brilliantly! This is such an incredible project, thank you for everything!

I've had to trim down the Alpha1 keyboard a bit (conversation keyboard was fine) to make space for the extra letters. The compact version looks like this (mouse icon leading to mouse menu for mouse buttons, and numbers/symbols menu for web browsing button etc):
https://ibin.co/w800/4Vgu8aez4yAI.png
I'm fairly happy with how it looks, would appreciate your input too.

I also have a question regarding the button text. The Georgian words seem to be a bit smaller than the capped English text. Is there a way to perhaps increase the font size for the georgian text? Example images below:

English (BACK) - https://ibin.co/w800/4VgumYQFlOT1.png
Georgian (უკან) - https://ibin.co/w800/4VgwV1KupRMu.png

Finally, I would also like to attempt conversion of the simplified keyboard (the one with sectors) - though I can attempt this after first merging this version. Could you perhaps provide any guidance on how I could do this? The guide I followed at https://github.com/OptiKey/OptiKey/blob/master/docs/Localize.md doesn't specify this.

Cheers!

**Comment by JuliusSweetland** [comment]
@OneBadNinja No problem. The screenshots look really good. I suspect the text is small as it will all scale together so that all key text is the same size. Do you have a key with a long string on it that is forcing down the size of all keys? (this sizing is only specific to a single keyboard, so a long Text string in the Alpha keyboard would not be impacting the Text strings in the Menu, for example).

Can you create a Pull Request when you are happy with the changes you have made so far?

In terms of the simplified keyboard, I would copy the SimplifiedAlpha1 and SimplifiedConversationAlpha1 keyboards from English to your new Georgian folder. Change the namespaces, and then change over the letters. The big difficulty is going to be getting Georgian to fit in the key layout used in the English simplified keyboard, where one key drills down into 3 keys, each of 3 letters. You might have to increase the number of keys which have letters on them to achieve this.

If it helps to explain how it works: the simplified keyboards start out with the Settings.Default.SimplifiedKeyboardContext value set to null. They display their default values, e.g. https://github.com/OptiKey/OptiKey/blob/e6ad0b1a55ae9162922230ed8f87918499aa6622/src/JuliusSweetland.OptiKey/UI/Views/Keyboards/English/SimplifiedAlpha1.xaml#L46

If the user clicks that key the handler of that key value (KeyValues.SimplifiedKeyboardAlphaGroup1AllKey) sets the context to SimplifiedKeyboardContexts.AlphaGroup1All. The keyboard triggers then match the context and the keys change, e.g. to show https://github.com/OptiKey/OptiKey/blob/e6ad0b1a55ae9162922230ed8f87918499aa6622/src/JuliusSweetland.OptiKey/UI/Views/Keyboards/English/SimplifiedAlpha1.xaml#L52
This continues all the way down until you end up selecting a letter or number.

The tricky thing will be to draw out how the current keyboard works, and how many extra keys you might need for Georgian. You could then create new enum values for your extra contexts, and try to balance the keyboard so it moves up and down the contexts correctly. Let me know if you have questions - I know it's tricky, but I found it really helpful to write out the context and the key values before I started.

**Comment by OneBadNinja** [comment]
Hi Julius! Thank you, I'll let you know how I progress with the SimplifiedKeyboard. I have just checked and can confirm I had a long string for "multi-key selection" which I have now shortened on Transifex (the one with the linebreak after multi-key if I'm correct). If you could please send over the new .resx file I can simply update and create the pull-request with the text-size taken care of. 

Thanks!

**Comment by JuliusSweetland** [comment]
@OneBadNinja here you go. N.b. you'll have to rename the file and extension...

[for_use_optikey_english-strings-from-resourceresx_ka.resx.txt](https://github.com/OptiKey/OptiKey/files/2840951/for_use_optikey_english-strings-from-resourceresx_ka.resx.txt)

**Comment by OneBadNinja** [comment]
Thank you Julius! I just realized I could edit it directly in a text editor so I did that but they should be the exact same! Created the pull request now :)

**Comment by OneBadNinja** [comment]
Hi Julius. I've run into some issues implementing the simplified keyboard which I hope you could clarify. I've attempted this on the Alpha keyboard for now. I have chosen to include a 4th block to preserve a 3-step process, and to make it easier for myself - I am not familiar with Csharp, but learning as I go along with your tutorials and reading the code. The fourth block has some symbols to preserve the 9-keys-per-block layout. Here is what it looks like:

https://ibin.co/w800/4Wex7Zo42SiN.png

And the usual layout is encountered in the second step (selecting one of the blocks):

https://ibin.co/w800/4WexaIhLqCxM.png

Unfortunately, only for this new block, I can't seem to go to the third step when hovering over any of these intermediate blocks. It works for all the other blocks (characters 1-9, 10-18, 19-27). All the changes I have done so far to get to this point are shown in the commit at my fork at:

https://github.com/OneBadNinja/OptiKey/commit/f44147158b998c6b86a04b9af264aec265561dd4

Please let me know if I may have missed anything related to the bindings that may be responsible for the last character sets intermediate block from not working correctly.

Furthermore, I also do not know how to include the simplified keyboard option in the "Words" menu of the management console. Could you please clarify how I could do this?

https://ibin.co/4WeyScuGQvz6.png

The only way I switch to simplified and back is by first selecting it on the English menu and then changing the language to Georgian.

https://ibin.co/4WezBtkMFzCT.png

Finally, I have noticed a small bug when switching from a language without the "Keyboard style for typing:" field to one that has it ie English. The dropdown menu has a red border and hovering over it gives a "Value not converted" message. This is easily resolved by just clicking the dropdown and selecting from there. Very minor thing, but I thought I would point it out. I don't think its related to my changes as I have reproduced this with the latest Release version of Optikey. 

Many thanks!

**Comment by JuliusSweetland** [comment]
@OneBadNinja I think the only thing you are missing are handlers for your new key values. Try adding your level 4 handlers under here: https://github.com/OptiKey/OptiKey/blob/75932cbda2e0004ad9cefeed052b73b59dd23c2d/src/JuliusSweetland.OptiKey/Services/KeyboardOutputService.cs#L327

To display the keyboard layouts in the Words tab I think you will need to add Georgian here: https://github.com/OptiKey/OptiKey/blob/e501c3b983174b996c3d3ab137ecdc0825b9b85a/src/JuliusSweetland.OptiKey/UI/ViewModels/Management/WordsViewModel.cs#L191

To your last question, I have just committed a fix. It's not perfect as there are potentially situations where this could happen, but in those situations I actually want the validation error (red outline on the drop down). Thanks for pointing it out!

Very minor change, but AlphaGroup4All is used by both Japanese and now Georgian, so could you include Georgian in the comment on this line: https://github.com/OptiKey/OptiKey/blob/dbc47e8930b7225e9a14e837fc8fe5c4610bb6f6/src/JuliusSweetland.OptiKey/Enums/SimplifiedKeyboardContexts.cs#L18

**Comment by OneBadNinja** [comment]
Hi Julius! It is all ready and working fine! I couldn't thank you enough! Submitted the pull request now! Here is what the keyboards look like:

Simplified Alpha:
https://ibin.co/4WphlJVB0uw6.png

Simplified Conversation:
https://ibin.co/4Wphqca09Wz4.png

For simplifed conversation I removed the calibrate button to preserve certain parts of the layout but it should be accessible from the menu either way. I'm happy with how it looks.

One question - naturally the "speak" key has no function for Georgian, but out of curiosity, how could I go about implementing this in the future? Would this be possible to do so? I suppose I would need a phonetic dictionary of sorts for the speech synthesis module being used ie http://www.speech.cs.cmu.edu/cgi-bin/cmudict for english

Many thanks!
Joey

**Comment by JuliusSweetland** [comment]
@OneBadNinja Excellent! Thank you. I've merged in all your changes and created a pre-release here: https://github.com/OptiKey/OptiKey/releases/tag/v2.23.0_pre-release-4

Could you please test it and let me know if everything works as expected. I will then release it.

After that is there any chance you could help promote OptiKey in Georgia? It would be great to help as many people as possible there.

**Comment by OneBadNinja** [comment]
Hi Julius! That's great! I can now confirm that everything works correctly, correct letters menus etc. The ESpeak voice is also working well! This is awesome! You may proceed with releasing it!

Of course I would like to help promote it. Quite a few patients in the hospitals according to our nurses so there would be a good start. I'm currently in the UK and can also promote it more proactively when I am home.

**Comment by JuliusSweetland** [comment]
@OneBadNinja Released as 2.23.0. Thanks again Joey.
