### ISSUE TITLE
Communikate folder location changes can't be cancelled

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#365]
- Open Management Console -> Words -> Enable CK -> Location of CK top .OBF file, change to a new location, confirm file dialog.
- Cancel Management Console
- The CK location has been changed (it shouldn't have been because the operation was cancelled)
- Launch Management Console again
- Without changing anything, click "Ok"
- You get the message "Restart required"

There's also some confusion in the labels vs. behaviour. It says "Location of CommuniKate top page .obf file", but the default is an ".obz" file and the file selector only allows other .obz files, which represent an entire pageset and not a top page. Is it supposed to work with both? (zipped obz and top page obf).

**Comment by Chopinsky** [comment]
I will take care of this

**Comment by JuliusSweetland** [comment]
@Chopinsky Thanks

**Comment by kmcnaught** [comment]
@Chopinsky @JuliusSweetland I just made a comment about this on the closed PR rather than the open issue - see https://github.com/OptiKey/OptiKey/pull/371

**Comment by JuliusSweetland** [comment]
@kmcnaught You make a good point. 

@Chopinsky I missed the call to "Settings.Default.Reload();" when I reviewed this. As Kirsty suggests I think a solution would be to remove the call to "Settings.Default.Reload();" when cancelling as the changes should NOT have been applied at that point. This requires a bit of clean up which Kirsty also describes:

"Communikate breaks this by making immediate changes to the settings rather than storing locally in the viewmodel until ApplyChanges() is called.

Is it possible to add a test that checks each view upholds this contract? Then we could just fix Communikate settings and any future breaking changes would be flagged by the test."

What do you think?

**Comment by Chopinsky** [comment]
As Kirsty mentioned in the comment to the PR, the reason to call `Reload()` is because that the code behind the "Location of CK top .OBF file" setting _will_ in fact save the file location to the persistent data once the change's been made, so to revert that change, we need to reload the settings with persistent data. 

So I can think of 2 fixing strategy:

1. As Kirsty suggested, we use `ApplyChanges` pattern in the "Communicate Settings" as well, and remove the call to `Reload`.

2. When we click "Ok", we find a way to save the changes to the persistent data, in that case the next time we call `Reload`, we will revert to the most recent updated settings. 

I'm find with either way, we could do both as well. Once we can reach a conclusion, I can make those updates tonight. Creating a test on this could be a bit difficult, at least I need to think more about how could make it work.

**Comment by JuliusSweetland** [comment]
@Chopinsky I should have removed the single line call to Reload() already, but I think the ApplyChanges pattern should be used with the Communicate Settings if possible, with the CK settings being stored in the Settings and saved to the persistent data at the same time as the settings are saved to disk (on close)? That would make the edit/save pattern the same for all settings.

What do you think?

**Comment by Chopinsky** [comment]
I agree, we should keep all the settings behave the same way. I would probably explore a few options to enforce the `ApplyChanges` pattern (maybe interface?), I will do it tonight after going back from work.

**Comment by JuliusSweetland** [comment]
@Chopinsky Lovely stuff. Thank you.

**Comment by JuliusSweetland** [comment]
@Chopinsky Your PR is now merged. Thank you.

Does this complete this issue?

**Comment by Chopinsky** [comment]
I would say yes, though Kirsty also mentioned about the label of that setting being confusing, since we only accept .obz files, while the label asks for .obf files. 

I'm not familiar with the history or evolving of this setting, so I left the label as is. If we don't care about that wording, or that wording is still meaningful, we can go ahead and close the issue.

**Comment by JuliusSweetland** [comment]
I think the label should be charged to reflect the file we actually
accept...

**Comment by kmcnaught** [comment]
@Chopinsky, thanks for the new fix. I just wanted to check, was it intentional to leave in the new confirmation dialog when cancelling the management console? It's a bit confusing as a user to get this confirmation even when you haven't changed anything, and even when you have, the call to action could be confusing, since "cancel" in the confirmation dialog could be interpreted as "cancel my cancelling" (this would be correct) or "yes, cancel my changes". I'm not sure the confirmation is required at all.

**Comment by Chopinsky** [comment]
So in the new popup, cancel means "yes, I want to stay and review", and okay means "sure, I don't want to save". 

I think we can work on the wording to make the popup message clearer, but I'm more inclining to save the settings to persistent data every time we apply changes, and then reload the settings from the persistent data after confirming the cancel popup, which will make more sense with the new popup.

**Comment by JuliusSweetland** [comment]
I believe the WindowManipulationService makes setting changes which are not
persisted until OptiKey exits, so reloading on management console
cancellation might lose some state information...

**Comment by JuliusSweetland** [comment]
Can this be closed?

**Comment by Chopinsky** [comment]
I'd vote for yes
