### ISSUE TITLE
CommuniKate keys with no Value no longer have a background colour

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#372]
@zelmon64 As discussed - this is an issue for the outstanding CK key issue.

**Comment by JuliusSweetland** [comment]
@zelmon64 Could you explain ShowOverScratchpadOveride more (also "Overide" is slightly misspelled). Shouldn't the sleep key behave like any other normal (not CK) key?

When you say the "sleep colour" this isn't a separate colour or behaviour is it? This should just be the disabled state of each key. Could I suggest making each key have a grey background (like the foreground colour of normal disabled keys) and a foreground colour of black (or a darker grey). The blank CK keys in your screenshots might confuse some users into thinking the keyboard is broken and not disabled.

Lastly regarding the dps:
1.Could you please remove the underscores? I don't tend to use them in property names.
2.Could you remove the Has_ColourOverride and the brush _ColourOveride properties and instead use value converters in the theme? You could use the same one to convert a string to a Brush class. As it's a class it is nullable so you could test the converted brush to see if it's null (which gives the same functionality as Has_ColourOverride) or use the brush (which gives the same functionality as _ColourOveride).

Happy to discuss.

**Comment by zelmon64** [comment]
@JuliusSweetland 

> @zelmon64 Could you explain ShowOverScratchpadOveride more (also "Overide" is slightly misspelled). Shouldn't the sleep key behave like any other normal (not CK) key?

This is for the **Speak** key, not the **sleep** key. In other CommuniKate / OBF communication boards the text is spoken by clicking on the scratchpad-like area. To replicate this with OptiKey I placed the **speak** key over the scratchpad. Normally this would completely hide the scratchpad. To make the scratchpad visible I removed the background from the speak key (made it transparent) and also only show the icon when the key is either current, selection is in progress or is is down (speaking). 

> When you say the "sleep colour" this isn't a separate colour or behaviour is it? This should just be the disabled state of each key. Could I suggest making each key have a grey background (like the foreground colour of normal disabled keys) and a foreground colour of black (or a darker grey). The blank CK keys in your screenshots might confuse some users into thinking the keyboard is broken and not disabled.

The original "sleep colour" was black for all CK keys (like the alpha keys). With how `KeyEnabledStates` was altered I could not find a way to distinguish between blank (disabled) keys and sleeping keys. Instead of adding some convoluted way to distinguish between the two I decided to make both the sleeping keys and the blank keys a solid colour. 

I can make the sleeping non-blank CK keys turn black/grey/etc instead when they sleep but the blank keys don't change state when sleep is activated. I could try to add something that has the same logic that  `KeyEnabledStates`  had but that seemed redundant since we just got rid of that.

> Lastly regarding the dps:
> 1.Could you please remove the underscores? I don't tend to use them in property names.

The underscores are just placeholders for the full names.

> 2.Could you remove the Has_ColourOverride and the brush _ColourOveride properties and instead use value converters in the theme? You could use the same one to convert a string to a Brush class. As it's a class it is nullable so you could test the converted brush to see if it's null (which gives the same functionality as Has_ColourOverride) or use the brush (which gives the same functionality as _ColourOveride).

The trouble with this is that I can't use brushoverride != null, I wanted a flag for != null so that the overrides could be applied after the defaults rather than the other way round (using brushoverride == null).

**Comment by JuliusSweetland** [comment]
@zelmon64 Thanks...
1. How did you achieve the speak key selective transparency on the current release? Maybe the speak key could use foreground, background, border (etc) overrides to be transparent and another dp to use the default theme styling called the key is current, selection in progress, or selected (down). Would that work?

2.Keys shouldn't really have 3 states; enabled, disabled and sleep. They should either be enabled or disabled, which includes disabled due to sleep. I believe all disabled keys should be styled in the same (or as similar) a way as possible. Let me know if you think this would look wrong.

3.Can you use logic in the theme to apply the overrides if they are not null (there are examples in the themes comparing values with {x:Null}), then the defaults using the current logic? That way you'd only need one override property for each colour, i.e. foreground, background, border, etc.

**Comment by zelmon64** [comment]
@JuliusSweetland 

1. In the the current release the speak key has `HasImage = True` and `HasSymbol = True`. The themes are set to target this combination. This is what I used [ShowOverScratchpadOveride](https://github.com/zelmon64/OptiKey/blob/918d7e9e984c2d1f7c79a366d47c5ff88eb0e465/src/JuliusSweetland.OptiKey/Resources/Themes/Android_Dark.xaml#L268-L279) for. I did initially try using the colour overrides to make it normally transparent but that seemed more complicated.

2. I've been mulling this over and I agree that the disabled keys should be styled in a similar way. I'm going to try a semi-transparent black / grey. This way the blank CK keys will still be coloured but they'll be different from the disabled non-blank CK keys.

3. The problem is that there doesn't seem to be a way to do `Value!="{x:Null})"` (it seems only possible to do `Value="{x:Null})"`). I've been thinking and it may be possible to do this with a converter like you suggested. Something like `IsNotNull` or `HasValue` that would return True. I wasn't sure at first because I'm not that familiar with converters.

**Comment by JuliusSweetland** [comment]
Understood thanks. I think value converters are the way to go rather.

**Comment by zelmon64** [comment]
@JuliusSweetland I managed to switch to using a converter without any trouble. I also applied the transparent black disabled layer but it's effecting all other keys for some unknown reason.

![image](https://user-images.githubusercontent.com/15001389/30700989-1dd452d4-9ee1-11e7-8643-7461f2aeb26a.png)

The code for the transparent layer is [here](https://github.com/zelmon64/OptiKey/blob/3a3bf1c0261cd14a284dcbe275861d7506d9c642/src/JuliusSweetland.OptiKey/Resources/Themes/Android_Dark.xaml#L460-L469) in case you know of something obvious. I'll keep looking. 

The extra writing that appears in the sleeping image is because the key text has been hidden by making it (the foreground colour) completely transparent. If having it show is a problem I can try to get rid of it by maybe changing its disabled foreground colour.

**Comment by JuliusSweetland** [comment]
Nothing obvious in that styling I'm afraid. Perhaps you can debug by
modifying the value converter temporarily to taken the whole key as the
value, and check the opacity dp. This would allow you to add a conditional
breakpoint based on the key value and check a normal key Vs a CK key. I
suspect the dp has a non-null default value.

One quick thing: I can't see the DisabledBackgroundOpacityOverride dp on
the key class?

**Comment by zelmon64** [comment]
Thanks for the tip. The [DisabledBackgroundOpacityOverride dp is just after DisabledBackgroundColourOverride](https://github.com/zelmon64/OptiKey/blob/3a3bf1c0261cd14a284dcbe275861d7506d9c642/src/JuliusSweetland.OptiKey/UI/Controls/Key.cs#L354-L361).

**Comment by JuliusSweetland** [comment]
@zelmon64 I don't know which value your OverrideHasValue converter is looking for, but the DisabledBackgroundOpacityOverride dp is a double, so it's default value will be 0. I suspect you want to change the default value to 100 and then override it to something lower for keys which you want to make semi or fully transparent.

I actually think the OverrideHasValue converter is irrelevant, as it is difficult to tell if the opacity has been overridden or not, unless you make the default value something non-sense, such as -1 (which I don't recommend). Instead perhaps just always apply the opacity and rename the dp to DisabledBackgroundOpacity as it's no longer an override.

**Comment by zelmon64** [comment]
@JuliusSweetland That did it thanks. I change the default value to 1.0 (fully opaque). I'll rename it to `DisabledBackgroundOpacity` as you suggest. 

![image](https://user-images.githubusercontent.com/15001389/30703934-fed4f390-9ee8-11e7-98f7-fb530ccd60ee.png)

**Comment by zelmon64** [comment]
That transparent text started to annoy me (and probably would be too confusing for the users). It was just a case of setting `DisabledForegroundColourOverride="Black"` 
![image](https://user-images.githubusercontent.com/15001389/30704465-b8331f3c-9eea-11e7-878a-433d2c725507.png)

**Comment by JuliusSweetland** [comment]
Looks good. I like it.

**Comment by zelmon64** [comment]
Here's the white version 
![image](https://user-images.githubusercontent.com/15001389/30706502-7761cd86-9ef0-11e7-8e22-6b3a0be01d44.png)
![image](https://user-images.githubusercontent.com/15001389/30706518-7fe50658-9ef0-11e7-8223-43748049f488.png)

I'll make a PR now.

**Comment by JuliusSweetland** [comment]
@zelmon64 That looks really clean. Nice work.
