### ISSUE TITLE
Calibration problem from conversation alpha keyboard

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#374]
It has been reported that attempting a re-calibration can cause OptiKey to become unresponsive:

Possible steps to reproduce the issue:
1.Use an EyeX tracker
2.Navigate to the ConversationAlpha keyboard (in English or Korean - possibly in any language)
3.Select the Calibrate (re-calibrate) key.
4.Complete the calibration and return to Optikey
5.Attempt to use Optikey. Apparently at this point it is unresponsive.

**Comment by kmcnaught** [comment]
Can confirm. Followed steps as described and at step 5, OptiKey isn't picking up any eye control. There's no evidence of any problems with the EyeX engine.

A subsequent interesting behaviour that may shed light into OptiKey's state is:

6. Use the contextmenu to go "Back". 
7. OptiKey disappears behind your other open apps
8. Bring OptiKey to the foreground by selecting it in the windows taskbar.
9. OptiKey is in the menu page, but with the fullscreen window state associated with the conversation page

**Comment by kmcnaught** [comment]
PS - note that the contextmenu's back functionality does work as expected when doing all other steps except the calibration.

**Comment by JuliusSweetland** [comment]
It sounds like when the user finishes the calibration the code I the Tobii
calibration class isn't detecting that the user has finished and/or isn't
restoring the correct state.

**Comment by kmcnaught** [comment]
I've taken a bit of a look at this. It seems the problem is calibrating via a maximised window. If you compare the behaviour between calibrating via the menu (which works fine) and via the conversation keyboard (which exhibits the above bug) then everything seems identical in terms of the EyeX calibration being successful, and you still get points published by the EyeX engine after calibration at step 5 above. 

If I launch a menu keyboard that is maximised, and then calibrate from there, you get the bug above. Conversely, if I launch a ConversationAlpha keyboard that isn't maximised, and then calibrate, you get correct behaviour. It seems like something in the Maximise() -> Hide() -> Restore() workflow isn't working, but I can't see anything obviously wrong.

Can you test this with a different eye tracker? It doesn't seem like it has anything to do with the EyeX, but it would be good to rule it out.

**Comment by kmcnaught** [comment]
One thing that isn't clear to me is how multiple levels of "restore" behaviour is handled. I'm not sure if I'm missing something or if this is a (related? separate?) bug. 

Whenever restore is called, then *if* current state is maximised/hidden/minimised, it will:
- save current state as (new) previous state; 
- set state to (old) previous state.

This seems reasonable if you're transitioning from a "normal" state to a [min/max/hidden] state and then restoring. However, in the case of calibrating via a maximised window, you're transitioning from (e.g.) docked -> maximised -> hidden -> restore() -> restore(). I think the two restores cancel each other out, which is why OptiKey gets hidden in step 7 above.

**Comment by JuliusSweetland** [comment]
The window manipulation service is a bit difficult in this area. I'll need
to investigate.

**Comment by JuliusSweetland** [comment]
This will be fixed in the upcoming pre-release. I'll prepare the release later this week.
