### ISSUE TITLE
Window state problems after calibrating in maximised mode

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#389]
This was already hypothesised in bug #374 . Tested on #7db76e5e

Using an eyetracker (EyeX for testing - don't think it matters):
1) Go to conversation alpha
2) Re-calibrate (this hides Optikey for the duration of calibration)
3) After calibration completes, OptiKey reappears. Click the back key
4) OptiKey disappears [bug part 1]
5) Bring OptiKey to the foreground by clicking on the taskbar icon
6) Click the back key
7) OptiKey returns to the menu, but maximised [bug part 2]

This is almost certainly (at least partially) to do with the maximise -> hide -> restore -> restore workflow as mentioned in bug #374 .

**Comment by JuliusSweetland** [comment]
@kmcnaught This is probably to do with the call to the restore (after calibration completes) saving the previous state (minimised) as the previous state. When the back key is used the previous state is probably restored to hidden and the previous state saved as maximised. I think the fix is to not store the previous state when restoring from minimised.

**Comment by JuliusSweetland** [comment]
Another reported version of this issue:

optikey is minimize when dad do this process

1. go to conversation keyboard
2. select re-calibration button
3. calibration done
4. dad type some word.. or just select back button
5. OptiKey is go away suddenly
6. if we restore OptiKey from Taskbar, than it full cover the window

**Comment by JuliusSweetland** [comment]
@kmcnaught @Simyu Fix for this bug included in the 2.11.0 pre-release 6: https://github.com/OptiKey/OptiKey/releases/tag/v2.11.0_pre-release_6
