### ISSUE TITLE
OptiKey starts holding down shift key

### ISSUE THREAD

**Issue by eulercamposbarros** [OptiKey/OptiKey#396]
When OptiKey starts, the left shift is down for ShiftAware keyboards. It results in a shift hold that affects all other programs on the system.

I guess is a good idea to start the program with shift pressed to allow first letter capitalization, but this behavior (shift down) should not affect other programs since the program was just launched and no other key was pressed on it.

This problem happens on version 2.11.0.0.

**Comment by JuliusSweetland** [comment]
@eulercamposbarros Thank you for raising this, but I don't consider this a bug as it is very much deliberate. When a user of OptiKey opens the program in a keyboard which is ShiftAware I think it is correct behaviour for SHIFT to be down so that when they start typing the first character would be capitalised. This will only occur in keyboards where the intention is for OptiKey to be outputting text to other programs (i.e. it will not occur if the user starts in a conversation keyboard, or moves into a conversation keyboard). As OptiKey will be their main/only form of interaction with the computer I think this is fine.

I suspect your use case is that you are primarily using a physical keyboard and mouse, and so when OptiKey opens it "interferes" with your SHIFT key state, which is confusing if you don't know why. This isn't the use case of OptiKey users as they wouldn't be able to (and it doesn't really make sense to) use a blend of physical keyboard and OptiKey for keyboard simulation.

If I am misunderstanding the problem please let me know.  Cheers.

**Comment by eulercamposbarros** [comment]
You are absolutely right Julius on the assumptions about my use case.

I just found this behavior odd and suggested a change based on my recent use of OptiKey, but after your explanation, it became a little more clear to me how the final user sees this feature.

Thanks for your time and, if you want, you may close this issue.
