### ISSUE TITLE
Suggested new keyboard layout

### ISSUE THREAD

**Issue by sheeva700** [OptiKey/OptiKey#427]
@JuliusSweetland 
First sorry for my silence. I was hospitalized. Now i'm back with brain full of idea regarding Optikey . I have to say that a lot of people was really interested about the simplicity of use Optikey there. (doctors, nurse,...) :)
To be honnest i had also tobii comunicator 5 .(a crapy software when you try to use it under. windows desktop). That's for th story. During the loooong days in hospital i had time to watch plenty of movies. So i fall on a movie (far from oscar award) but, movie was showing "ouija board"... And i realized that the layout will be perfect for optikey ! I know, it's funny but look closer. Everything is there for everyday use. And very fast interactivity using short woard like yes, no, bye, ect... I don't know if is hard to complete. But i ask you to have a look open minded. Who know, if you contact a spirit it's not a bug but a hiden feature. ;-)
Here is an illustration http://images.mentalfloss.com/sites/default/files/styles/mf_image_3x2/public/oujia_6.jpeg?itok=gT__afPG&resize=1100x740

Dominique.

**Comment by Sheeva007** [comment]
Of course, forget the fonts typo and horrible illustration. I just try to give you an idea. ;-)

**Comment by JuliusSweetland** [comment]
![image](https://user-images.githubusercontent.com/4722561/36202417-a63e401e-117b-11e8-94a6-cd83e35038ba.png)
(image copied here)

**Comment by annakirkpatrick** [comment]
@sheeva700 Do you think that the fact that the alphabetic lines are curved is important here? If straight rows would work, then I think this should be pretty easy to put together using the new(-ish) dynamic keyboard feature.

If I put together such a keyboard, would you be interested in testing?

**Comment by OutsourcedGuru** [comment]
Rather than creating another issue, I decided to post here. Apologies if my take on this runs differently than the existing model or from the suggestions above.

The standard QWERTY keyboard design was based upon the concept of a (right-handed) two-handed typist. I learned how to type on an old Underwood typewriter in high school, btw. Honestly, though, this new concept of OptiKey should divorce itself completely from the QWERTY layout since no hands/fingers are here in use. Those original positions were based upon the frequency of vowels and consonants in the English language as well as the need for common pairing such as "ch", "sh", "en" and such to be on alternating hands.

A new keyboard should introduce those common pairings and alphabetic character frequencies into something which minimizes the distance. Personally, I would put all the vowels in a center ring around the SPACE character. A ring of letters like "s, t, n, r..." would then surround those but in such a way that it minimizes travel distances for word formation. In fact, I might suggest that the layout be mathematically divined by programmatic trial and error: randomly create a layout, then iteratively spell the 5,000 most common words programmatically, measuring the accumulative distance. The winner of this contest would then be reviewed for adoption.

**Comment by annakirkpatrick** [comment]
@OutsourcedGuru This isn't a bad idea, though it would be tricky to implement with the current code. Right now, everything is constrained to be on a grid.

I actually have designed a keyboard (subject to that grid constraint) that puts most frequent characters closest to the center of the screen (note that the keyboard won't generally cover the whole screen). My "hacker keyboard" was designed for programming and therefore use frequency data from source code in a couple of different languages. I did make some compromises for learnability, and I also made some guesses about the frequency of certain other keystrokes (e.g. tab, which is commonly used for completion in terminals or editors). I only considered frequency data for individual characters, not pairs or triples of characters, so I'm sure you could do better by analyzing that data as well. At any rate, my hacker keyboard is [here](https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey/Resources/DynamicKeyboards/BigHackerKeyboard.xml). And the dynamic keyboard support makes it easy to specify custom keyboards laid out however you want.

One other point to consider: for most users, you won't be able to fit all of the characters on one keyboard. I got all of the typeable characters onto one keyboard because I am using a large monitor, have good control of the muscles controlling my eyes, and am working in controlled environments (minimal sunlight creating interference, for example). In less optimal situations, it's definitely necessary to spread out the characters on to multiple sub keyboards in order to keep the keys large enough.
