### ISSUE TITLE
bi-color keyboard

### ISSUE THREAD

**Issue by Sheeva007** [OptiKey/OptiKey#463]

**Comment by Sheeva007** [comment]
@JuliusSweet beige lighter for Alpabetical keys and darker for function keys
Witch can render your keyboard clearer and more aesthetique keybord.

Dominique.

**Comment by JuliusSweetland** [comment]
@PopeSpaceous Hi. Rather than using the SharedSizeGroup (which is an attached property from the Grid class and is only used with sizing), you can instead bind to the Key's HasSymbol property with something like this:

`Binding="{Binding Path=HasSymbol, RelativeSource={RelativeSource AncestorType={x:Type controls:Key}}}" `

I would make the change in the KeyBorderStyle (in a new theme that is designed to be two tone) and add new style setters to set the Background based on whether the key has a symbol or not. I think the disabled key logic should override the two tone behaviour, so define your logic above the existing disabled key logic.

Does that make sense?
