### ISSUE TITLE
Add alphabetical and simplified keyboard layouts for German

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#473]

**Comment by JuliusSweetland** [comment]
Excellent, thanks Anna. The existing German keyboards will give you all of
the expected keys and diacritical marks.

**Comment by annakirkpatrick** [comment]
Regarding the alphabetic layout, there is a question about where to position the "extra" keys (that is, those that don't occur in the English alphabet).

I'm guessing one of the main applications of the alphabetic layouts is for children, so I asked one of my contacts how German children learn the alphabet. He grew up in Germany, and he told me that the "extra" letters are learned as part of the alphabet and are placed right after the letters they are derived from. So, the alphabet as learned by German children looks like:

a **ä** b c d e f g h i j k l m n o **ö** p q r s **ß** t u **ü** v w x y z

Specifying the alphabet this way, as opposed to using umlaut as a modifier, requires 2 additional keys, but I'm pretty confident I could tweak the layout to make this work. The question is whether or not this is a good idea.

I see two main options:
1. Arrange the alphabetic layout with the English alphabet plus ß and place the umlaut modifier key at the end or perhaps at the end of a row.  This has the advantage of being consistent with the QWERTY-style layout that already exists.

2. Arrange the alphabetic layout as listed above, with individual keys for each character with an umlaut. This has the advantage of being consistent with the way the alphabet is taught to German children.

From my perspective, either option seems valid, but I wanted to solicit input before making a decision. Additionally, are there technical reasons why including ä, ö, and ü would be difficult or undesirable?

**Comment by JuliusSweetland** [comment]
Hi Anna. No there is no reason for not including all keys explicitly. I
tend to lean towards fewer keys so the remaining keys can be as large as
possible, but when there are only 3 or 4 extra keys it doesn't really make
a difference. In this instance I would lean towards including all keys
explicitly. Thanks.

**Comment by annakirkpatrick** [comment]
I've got the alphabetic layout up and running. Nothing too tricky there.

With the simplified layout, though, I've run into some problems with the umlaut.

I decided to include umlaut as a modifier, as is done on the default German keyboard.  (The alternative is to separately include the three vowels with umlauts. This would require some nontrivial reorganization of the keyboard layout, which I can do, but it would inevitably result in smaller keys and/or a deeper selection tree.)

I placed the umlaut on the home screen next to shift. (I replaced the recalibrate key. This function, after all, is still available with just two selections.) It makes sense to me to place the umlaut next to the shift key because they both act as modifiers.

And here's where I need help. Unlike the shift key, the umlaut key does not act like a modifier when multiple keys must be selected in order to reach the desired character. Instead, when I press the umlaut, all of the other keys (except shift) are greyed out because they don't exist with umlauts.  See the screenshot below.

![image](https://user-images.githubusercontent.com/33188271/43097095-090be0b8-8e89-11e8-9454-85c4baee812c.png)

@JuliusSweetland Can we make the umlaut key behaves similarly to the shift key in order to make it work with simplified keyboard? Or would you recommend a different approach?

**Comment by JuliusSweetland** [comment]
Hi Anna,

If there are 3 letters which can be modified with the umlaut, why not
replace the content of the 3 letter keys when the umlaut is down to the
associated keys, and revert back if umlaut is released without selection?

**Comment by annakirkpatrick** [comment]
@JuliusSweetland That make complete sense.  I'll work on it.

**Comment by JuliusSweetland** [comment]
Great! Thanks very much.
