### ISSUE TITLE
Manual mode does not work properly when keyboard key trigger mechanism is used

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#524]
# How OptiKey was being used

Version 2.20 had just been installed. An able-bodied helper was attempting to help me with configuration. I instructed him to enable manual mode by right clicking on Optikey and selecting manual mode. Manual mode was successfully enabled.

# What the user expected to happen

I expected that my helper would be able to activate keys by clicking on them.

# What the user actually experienced

The orange highlight did follow the mouse, but clicking on keys did nothing. Pressing my trigger button (mapped to keyboard key) gave message "I cannot detect where you are directing your attention…" (Even if I was sitting in front of the screen and the Tobii tray icon indicated that my gaze was detected.)

# Version
 - Operating system and version: Windows 10 (64-bit)
 - OptiKey version 2.20.0.0

# Steps to reproduce the issue

1. Configure Optikey to use keyboard key trigger mechanism. I am using key F 23, but I have verified that the same behavior occurs when using key "I".
2. Right-click on Optikey and select "Toggle Manual Mode." Click yes in the dialog box.
3. Observe that the orange highlight follows your mouse cursor when you move it across Optikey.
4. Try to click on any key. Notice that nothing happens.
5. Try pressing your trigger key. Note the resulting message.

# Any other information that helps to describe and/or reproduce the problem

Just a quick note that this bug is not a big deal for me personally, so, as far as I am concerned, there is absolutely no urgency in this request. It is a very rare situation when I would have an able-bodied helper helping me with Optikey. (Most of the time I am quite independent with gaze and speech input. When I need help or am collaborating, I just hand my helper a physical keyboard.)

Nonetheless reporting this because I know it could be an issue for some. Would be happy to test any fixes, as I have the hardware to do so easily.

# Screenshots

N/A

**Comment by JuliusSweetland** [comment]
@annakirkpatrick Hi Anna. Please try the 2.21.0 pre-release here and let me know if that fixes this issue: https://github.com/OptiKey/OptiKey/releases

**Comment by annakirkpatrick** [comment]
@JuliusSweetland I downloaded the prerelease that you linked to above, and I saw the exact same behavior as I described in the original bug report. I did turn on debugging mode and save a log, in case that contains any clues.
In this log file:
1. Launch OptiKey.
2. From the dynamic keyboard menu (my start screen) use gaze and switch to select my custom dynamic keyboard.
3. Right click on OptiKey to pull up the context menu. Click on "enable manual mode" and click yes to the prompt. The large message box appears indicating that manual mode has been enabled.
3. Move mouse cursor over the Q key. Left click multiple times. Repeat with a few other alphabetic keys. No input to the target application is generated at any point.

Though this log only shows me working with a dynamic keyboard, I have verified that same behavior occurs with the standard keyboards.

[OptiKey.log](https://github.com/OptiKey/OptiKey/files/2637365/OptiKey.log)

**Comment by kmcnaught** [comment]
Okay, I know what's happening here but my RX knowledge is wearing a bit thin to know whether my proposed fix is sufficient. Here goes...

TriggerSources have a `IObservable<TriggerSignal> Sequence` which relies on a `PointSource`. The `PointSource` gets swapped out via `ToggleManualMode` which requires that the `Sequence` is disposed and re-acquired.  

With the `KeyFixationSource` (which has the correct behaviour), once the selection trigger subscription is disposed in `InputService.DisposeSelectionSubscriptions` , the `Sequence` is automatically disposed too, and this included setting `sequence = null`. With all other trigger sources (which don't work with manual mode) the `sequence` remains non-null at this point and doesn't ever get re-created.

In the `KeyFixationSource`, the sequence is created using the following constructor
`Observable.Create<TriggerSignal>(Func<IObserver<TSource>, IDisposable>)` which allows for an explicit dispose method for the sequence. The other trigger sources use a different pattern, combining multiple observables which have been created using an `Observable.FromEventPattern` pattern.

It may be sufficient just to add a 
```
.Finally(() => {                            
  sequence = null;
});
```
to the sequence observable. This does give the correct behaviour, and I can't obviously see anything that isn't being disposed of. I think the issue is literally just that it's not being set back to null. But I definitely don't understand this RX stuff well enough to be certain so would appreciate @JuliusSweetland's eyes on it.

**Comment by JuliusSweetland** [comment]
@kmcnaught Your solution to add the finally handler looks good, but I don't fully understand the significance of the sequence being set to null (or not). What impact does this have?

**Comment by kmcnaught** [comment]
@JuliusSweetland in the getter for Sequence there's this:

```
    if (sequence == null)
    {
        var keyDowns = Observable.FromEventPattern<KeyEventHandler, KeyEventArgs>( ... )                    
        var keyUps = Observable.FromEventPattern<KeyEventHandler, KeyEventArgs>( ... )
        
        sequence = keyDowns.Merge(keyUps). ... etc
     } 
     return sequence;
```

Currently (without my proposed fix) the `keyDowns` and `keyUps` observables are being correctly disposed (I can see that the `removeHandler` argument is called) and the `sequence` observable is being terminated (I can add a `Finally` handler and it gets called) but without setting to null the sequence never gets reacquired. Does that make sense?
