### ISSUE TITLE
Magnetic cursor behaving erratically after 15 minutes

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#547]
# How OptiKey was being used
I was using the magnetic mouse only to control the mouse cursor using a PCEyeMini (to test an webapp that requires gaze-controlled-cursor as input). I was also recording the desktop with useloom via Chrome (video available on request but I'm not sure it helps)

# What the user experienced
After 10-15 minutes, the cursor started behaving erratically. Jumping around, and not being received correctly by the webpage. ~15 seconds later, OptiKey gave the error:

> System.Exception: Some simulated input commands were not sent successfully. The most common reason for this happening are the security features of Windows including User Interface Privacy Isolation (UIPI). Your application can only send commands to applications of the same or lower elevation. Similarly certain commands are restricted to Accessibility/UIAutomation applications. Refer to the project home page and the code samples for more information.

The error did not contain any newlines and was very difficult to read. 

# Version
 - Windows 10
 - OptiKey version 2.19.0.0 + small hack to put magnetic cursor on the minimised mouse menu. 

See line 238 of attached log

[OptiKey.log](https://github.com/OptiKey/OptiKey/files/3093457/OptiKey.log)

**Comment by JuliusSweetland** [comment]
@kmcnaught Hi Kirsty. This is the source code behind that exception:
https://github.com/michaelnoonan/inputsimulator/blob/244bbf211601438408c9d0ff8c008d0ba0aad4c9/WindowsInput/WindowsInputMessageDispatcher.cs#L25

Under the hood this is trying to call this:
https://github.com/michaelnoonan/inputsimulator/blob/244bbf211601438408c9d0ff8c008d0ba0aad4c9/WindowsInput/Native/NativeMethods.cs#L91

I presume the issue is that you are running a version of OptiKey WITHOUT UiAccess (unless you are signing and installing your own version?). This article suggests that you need UiAccess for SendInput to work under some circumstances: https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/b68a77e7-cd00-48d0-90a6-d6a4a46a95aa/sendinput-fail-beause-interface-privilege-isolation-uipi-and-integrity?forum=windowsaccessibilityandautomation

Can you replicate the problem?

**Comment by kmcnaught** [comment]
Okay, that's helpful. Indeed it will have been an unsigned version, so that's a likely culprit. However, I'm struggling to think what the circumstances could have been that caused the problem - seeing as I'd been using it fine for a while, and as far as I'm aware I didn't do anything differently. I'll try to replicate, and then test against a signed version of Optikey. 

I'll also look at inserting some newlines into third-party exception messages :)

**Comment by JuliusSweetland** [comment]
New lines would be great. I'd imagine with the auto don't sizing it was
pretty small!
