### ISSUE TITLE
Program Selectively Ignoring Keystrokes from Optikey

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#584]
# How OptiKey was being used
Using Optikey as my keyboard, I open a phone mirroring application called Scrcpy. Once the program is open, I try to type, but the only characters Scrcpy responds to are numbers.

# What the user expected to happen
Scrcpy does work normally with other on-screen keyboards, so I expect the alphabet and navigation keys to be recognized.

# What the user actually experienced
The only characters Scrcpy responds to are numbers.

# Version
 - Operating system and version: Windows 10
 - OptiKey version v2.24.0

# Any other information that helps to describe and/or reproduce the problem
https://github.com/Genymobile/scrcpy

**Comment by JuliusSweetland** [comment]
@AdamRoden By default OptiKey uses methods to work out how to publish the correct virtual key code, which corresponds to the key position of the character you are trying to type. Simply put if you are using an English UK keyboard layout in Windows and type the "t" key, then OptiKey publishes a press event for the 5th key in the top row (or wherever "t" is located).

3 questions/ideas:

1.Are you using an unusual keyboard layout (as specified in Windows)?
2.Do you have a modifier key down in OptiKey, or in any other application, for example CTRL, SHIFT, WIN KEY? These change the way Windows (and other applications) interpret the typed characters.
3.Can you try changing a setting in the "Other" tab of the Management Console: Turn off Publish Virtual Key Codes For Characters. This changes the behaviour to explicitly output the character typed, rather than the keyboard key positions. This may help.

Let me know how you get on.

https://github.com/OptiKey/OptiKey/blob/f67d0838e654e654f5941830f976c58ff7ee07fd/src/JuliusSweetland.OptiKey.Core/Services/KeyboardOutputService.cs#L1062

**Comment by AdamRoden** [comment]
None of the 3 ideas led to a solution. 

My guess is Scrcpy not utilizing the language keyboard defined in Windows or something with the way the Android Debug Bridge works.

I am able to work around the issue by using AutoHotkey to intercept and resubmit the keystrokes.

**Comment by tqphan** [comment]
Hi, the reason OptiKey can't send keys to certain application is because there is a bug in InputSimulator library. It does not send, the correct scancode. Only the virtual key is sent. Some applications require the scancode to work correctly. I would recommend switching to a more active fork of InputSimulator such as https://github.com/TChatzigiannakis/InputSimulatorPlus/tree/master/WindowsInput

**Comment by JuliusSweetland** [comment]
@tqphan Hi Tom. Thanks very much. I will upgrade OptiKey to use the InputSimulatorPlus. There is a more up to date equivalent, but this targets .Net Standard, which is not currently compatible with my solution.

**Comment by JuliusSweetland** [comment]
@tqphan A new version has been created here for testing: https://github.com/OptiKey/OptiKey/releases

**Comment by alexandre-mbm** [comment]
Have it entered to current stable release?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm Yes, new version 2.30.0 is up to date with all changes. Please download and try it out.
