### ISSUE TITLE
Possible Bug: Sizing Issues

### ISSUE THREAD

**Issue by bigmutty** [OptiKey/OptiKey#691]
# How OptiKey was being used

I created a Dynamic Keyboard and added a Dynamickey to navigate to the ConversationAlpha1Keyboard.

# What the user expected to happen

I expected Optikey to open the ConversationAlpha1Keyboard in fullscreen mode.

# What the user actually experienced

The ConversationAlpha1Keyboard opened in fullscreen mode for a second but then it sized the keyboard to the previous keyboard's size (docked to the left side).

# Version
 - Windows 10
 - OptiKey version 3.0.6.0

[VerticalQWERTYKeyboard.zip](https://github.com/OptiKey/OptiKey/files/4922446/VerticalQWERTYKeyboard.zip)

**Comment by JuliusSweetland** [comment]
@AdamRoden Hi Adam - any idea here?

**Comment by AdamRoden** [comment]
No idea, but I can take a look.

**Comment by JuliusSweetland** [comment]
Thanks very much

**Comment by AdamRoden** [comment]
@JuliusSweetland 
Well, this one is going to be fun. I may be a little off, but the flow goes something like this:
The resizing of the conversation keyboard from full screen to docked happens because when we leave a dynamic keyboard we always reset to the persisted window settings, which also drops a message to Windows for the appbar, which asynchronously responds triggering us to resize our window. 
To properly fix this, I think we need to tie the built-in keyboards to an enum so we know whether or not we need to register a new appbar. 
Julius, you know the built-in keyboards better than me. Is there already something I can use?

**Comment by JuliusSweetland** [comment]
Possibly yes. I'm going to be busy tomorrow, but I'll take a look by the
weekend and reply again

**Comment by kmcnaught** [comment]
when you look at this, can you please also bear in mind [issue 685](https://github.com/OptiKey/OptiKey/issues/685), which smells like it might have a similar cause...

**Comment by AdamRoden** [comment]
@kmcnaught @JuliusSweetland I'll look at 685 as well. I have time tonight and tomorrow, so I hope to get to the bottom of both.
If all I need to worry about on 691 are the two versions of the conversation keyboard, then I think I have a solution.

**Comment by JuliusSweetland** [comment]
@AdamRoden @kmcnaught Pre-release here: https://github.com/OptiKey/OptiKey/releases/tag/v3.0.6_pre-release_3

It would be great if you have a chance to test

**Comment by bigmutty** [comment]
That fixed the keyboard to the appbar, but I didn't mention a cosmetic side effect. When I return to the dynamickeyboard, the key that linked to the conversation keyboard is blue with a lock icon, but it still works.

**Comment by JuliusSweetland** [comment]
@bigmutty Hi Daryl. Any chance you could post the steps to reproduce that, ideally with screenshots? Thanks

**Comment by bigmutty** [comment]
First I select the key to navigate to the Conversation Keyboard.
Then when I back out the Conversation Keyboard, the key used to change to the Conversation Keyboard appears to be locked but still works.
![image](https://user-images.githubusercontent.com/67619174/88012854-8de06580-cae0-11ea-95cb-06bc71b1d293.png)

Even when I go to my QWERTY keyboard, the key in that location has the lock icon.
![image](https://user-images.githubusercontent.com/67619174/88013959-5de69180-cae3-11ea-8354-1d98870d98c5.png)

Once I select that key again it goes back to normal.
![image](https://user-images.githubusercontent.com/67619174/88013334-c0d72900-cae1-11ea-974d-970fe4a238ca.png)

**Comment by JuliusSweetland** [comment]
@bigmutty Hi Daryl. Could you please start a fresh run of Optikey, replicate this issue, and then send me the log? Thanks.

**Comment by bigmutty** [comment]
[OptiKeyPro.log](https://github.com/OptiKey/OptiKey/files/4968893/OptiKeyPro.log)

**Comment by JuliusSweetland** [comment]
@bigmutty I'm slowly getting around to this (!) - could you send me the dynamic keyboards you are using pls? Thanks Daryl.

**Comment by JuliusSweetland** [comment]
@bigmutty Right, that took a while! The problem is the way a command key locks down the key, runs the commands, and then sets the key back to Up. With the Conversation keyboard the issue is that the SimulateKeyStrokes state is changed, which triggers all the key states to be stored and then set back to default values. When you leave the Conversation keyboard SimulateKeyStrokes changes again and the previous values are restored. Unfortunately, the key down state that is stored is LockedDown and this is what is then restored.

example log entry:
2020-07-30 21:23:41,577 [ 1] INFO  JuliusSweetland.OptiKey.Models.KeyStateServiceState: Storing key down state of '[Char:R|Unicode:U+0052][Char:1|Unicode:U+0031][Char:2|Unicode:U+0032][Char:-|Unicode:U+002d][Char:C|Unicode:U+0043][Char:2|Unicode:U+0032]' as 'LockedDown'.

I'm trying to figure out a way around this!

**Comment by JuliusSweetland** [comment]
@bigmutty Right, I've shifted a couple of lines around. I'm preparing a new version of the 3.0.6 pre-release. If you could test that my change hasn't broken anything else, that would be great.

**Comment by JuliusSweetland** [comment]
@AdamRoden Hi Adam, I've shifted a couple of lines around to prevent this bug - could you please check your dynamic keyboards, especially those with multiple command keys, to make sure nothing obvious is broken? https://github.com/OptiKey/OptiKey/releases/tag/v3.0.6_pre-release_5

@kmcnaught Kirsty could I ask you to kick the tires as well? Hopefully this is the final candidate for a full release.

Thanks!

**Comment by bigmutty** [comment]
That fixed the locked key issue, but just yesterday I found another sizing issue regretfully.

The first time I minimize Optikey from my dynamic keyboard, it's normal sized, but each time I minimize after that it gets quite a bit smaller (probably 20% the size).

[OptiKeyPro.log](https://github.com/OptiKey/OptiKey/files/5004125/OptiKeyPro.log)
Well, that time it was small the first time I minimized Optikey.

**Comment by JuliusSweetland** [comment]
@AdamRoden Hi Adam, is there any chance you could take a quick look at this new sizing bug? Daryl's dynamic keyboards are attached in a zipped file

[Keyboards.zip](https://github.com/OptiKey/OptiKey/files/5005892/Keyboards.zip)

**Comment by AdamRoden** [comment]
@JuliusSweetland I might be able to look today, otherwise I can definitely look tonight.

**Comment by JuliusSweetland** [comment]
Ideal, thanks!

**Comment by JuliusSweetland** [comment]
@AdamRoden Hey Adam. Did you have any time to look into that bug? Thx

**Comment by AdamRoden** [comment]
@JuliusSweetland Sorry, but my mental energy has been in short supply and I haven't been able to give it the focus I had intended. However, I do think I can fix it by this weekend. My theory on the cause is that earlier in the year I wrote some code to specifically fix Minimized state, and that now my most recent update countered that code.

**Comment by JuliusSweetland** [comment]
Great, no rush. I'm not chasing, just following up before I forget! Thanks
Adam.

**Comment by JuliusSweetland** [comment]
@AdamRoden @bigmutty @kmcnaught Right, hopefully the final pre-release version of 3.0.6 is here if you all have a few minutes to install and kick the tyres: https://github.com/OptiKey/OptiKey/releases/tag/v3.0.6_pre-release_7

Thanks all for your effort on the sizing bug, which Adam should now have fixed.

**Comment by bigmutty** [comment]
The sizing issues appear to be fixed!

**Comment by kmcnaught** [comment]
Looks good to me

**Comment by JuliusSweetland** [comment]
Great, thanks all. That's released!

**Comment by AdamRoden** [comment]
Awesome! I've been revamping my dynamic keyboard layouts and management console settings, and with what I have now I would say that in terms of performance and usability it blows Tobii out of the water. =-D I can't wait to share.

**Comment by JuliusSweetland** [comment]
I'm really looking forward to seeing that. I'd love to get your thoughts on
what changes could be made to the default settings as they are all based on
my best guesses and could do with some refinement I'm sure!

**Comment by JuliusSweetland** [comment]
One other thing to think about will be how to provide the new settings to
existing users as they optikey installer does not override existing
settings. As the default on a brand new install, but also as a guide? Or
maybe a script which users can run? Or even a one time upgrade code path
which asks the user and then applies setting changes if they want them.
Worth a discussion.
