### ISSUE TITLE
Mouse magnifier does not center on selection point in v3.0.6.0

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#711]
Upgraded from 3.05 to 3.06 and now the magnify pop-up window is always appearing offset to the right. This makes the feature unusable.

**Comment by AdamRoden** [comment]
I could be wrong, but I suspect this is somehow related to the modifications to allow manual resizing. @kmcnaught do you have any thoughts?

**Comment by kmcnaught** [comment]
Okay, this is a _really weird_ one. @JuliusSweetland for some rubber ducking, in the hope you have a clearer idea of how the MagnifyPopup's layout works. 

This bug was introduced in 61800d423a, where I do nothing more than occasionally turn off the main window's resize grips so I can avoid the logic of "what does the user mean when they resize in this minimised/collapsed state". (note that the addition of this line is irrelevant to the issue:  `    if (getWindowState() != WindowStates.Docked) return;` )

The behaviour is such that if you have not ever minimised or collapsed Optikey this session, the mouse magnification will work correctly. As soon as the resize grips are turned off (by minimising or collapsing), the magnify popup ends up translated to the right. I believe that the translation is equal to the width of the popup (unless it gets curtailed by the edge of the screen). Most importantly, **none of the numbers in MagnifyPopup::SetSizeAndPosition are wrong.** While testing I've hardcoded a source point for consistent behaviour, and I cannot tell any difference at all between the properties of the MagnifyPopup in the case where it appears in the right place, and the case where it's offset. It just seems like changing the parent's ResizeMode has somehow changed the MagnifyPopup's sizing behaviour.

**Comment by JuliusSweetland** [comment]
What happens if the popup code temporarily sets the resize mode before attempting to size and position itself? Does that fix the behaviour?

**Comment by kmcnaught** [comment]
No, that doesn't help, because it's not the current resize mode that's the problem, but rather "has the resize mode ever been set to NoResize before this point"

**Comment by kmcnaught** [comment]
I'm increasingly getting deja vu with the unexplained behaviour in https://github.com/OptiKey/OptiKey/issues/670 . I'm wondering if there's something funky going on with the HorizontalOffset, which (a) causes #670 and (b) is somehow affected by changing the resize mode.

I've been trying to make a simpler minimal reproducable example, and I'm really confused about how the HorizontalOffset is supposed to work on a Popup. Here's a stripped-down popup with variable horizontal offset (video below). The vertical offset acts normally (is always exactly the distance from top of screen to popup) but the horizontal offset seems to be from the edge of the screen to the left hand edge (when `offset < width/2`) **but** from the edge of the screen to the **right hand** edge when `offset > width/2`. It feels like this inconsistency could be the root cause here (though I'm still at a loss for why the history of the resize mode would affect it...)
video: https://www.loom.com/share/486c6e58f99c45b9a1f2b534259cbf0b

**Comment by JuliusSweetland** [comment]
There was an issue a long time ago which was related to whether the computer was in tablet mode. That flipped the popup behaviour as it assumes that the user is right handed to popups appear to the left of what it thinks is the users right hand. Could there be something to that?

**Comment by kmcnaught** [comment]
Interesting. I can't think how that would be interfering here (I'm definitely not doing anything that should trigger tablet mode), but perhaps it is somehow linked to the resize mode?

It wouldn't explain why using Absolute positioning in a popup results in the strange horizontal offset behaviour though - I'm not doing anything other than changing the offset in that case.

**Comment by kmcnaught** [comment]
Oh, `Placement="Absolute"` seems to have the behaviour I was expecting, and `Placement="AbsolutePoint"` does weird corrections at the edges. Maybe I can make everything better with `Absolute` instead...

**Comment by JuliusSweetland** [comment]
Have a read of this, it's a question I posted on Stack Overflow a while ago: https://stackoverflow.com/questions/29448251/wpf-popups-alignment-point-inconsistent-top-right-or-top-left-with-placement

**Comment by JuliusSweetland** [comment]
@AdamRoden @kmcnaught New pre-release of 3.0.7 is available here: https://github.com/OptiKey/OptiKey/releases/tag/v3.0.7_pre-release_1

Thanks Adam & Kirsty for the sqift identification of the issue and fix. Very much appreciated!

**Comment by JuliusSweetland** [comment]
Releasing and closing.
