### ISSUE TITLE
Less aggressive update checking and notifying

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#724]
First, I greatly appreciate the effort put in to push out version 3.0.8.

However, version 3.0.9 looks to be something I don't really need. Still, I get a reminder of it every time I start OptiKey. This can be several times a day. Also, I imagine there are people who are not able to update OptiKey by themself if they rely completely on OptiKey to use the computer, since OptiKey needs to be closed when updating. They might still want to be notified when an update is available.

There is a tick box in the Management Console for update checking. After OptiKey has shown an update notification for the first time, I was thinking OptiKey could then not show the update notification for at least that day, but preferably for a few days, maybe for a week. Or there could be an additional setting for setting a value the user wants.

**Comment by AdamRoden** [comment]
@lsaranto I'm thinking a snooze option would be helpful. Ideally, it would be built into the update notification screen to allow the user to highlight a number (1-12) and time period, either hours or days. Then, Optikey could pop up the notification again after the snooze period has elapsed, perhaps when they know a tech user will be available.

**Comment by JuliusSweetland** [comment]
@lsaranto @AdamRoden All good suggestions. Being able to snooze the notification would be good, but I tend to assume that the user may not be able to manually interact with the computer, so this UX might be tricky. Alternatively we could suppress the check so it only happens every x days, configurable in the Management Console?

Worth considering: the number of recent updates is NOT normal. There were a series of bugs introduced and fixed in quick succession. Usually the release timing is every few months, meaning the notifications are not very intrusive. In this case the updates WERE required as there were some fundamental problems with the intermediate versions, so I would argue that, although annoying, the notifications are useful.

**Comment by JuliusSweetland** [comment]
Closing as the update frequency under normal circumstances is MUCH less often than it has been of late.
