### ISSUE TITLE
OptikeyChat and mouse not working with Tobii eye tracker 5

### ISSUE THREAD

**Issue by zloysmiertniy** [OptiKey/OptiKey#765]
Hello! I just bought a Tobii eye tracker 5 to use with Optikey. It worked when the input was the mouse, but it fails to open with Tobii et5. A message saying "bad news..." appears quickly and then disappears, I can't even read it. Can you tell me how to reset settings to try again? Can you tell me where to find a log so I can show it to you?

**Comment by theoractice** [comment]
OptiKey logs are saved at `%appdata%\Optikey\OptiKey\Logs` .
BTW Have you installed tobii's drivers? Sometimes you have to restart their services.

**Comment by zloysmiertniy** [comment]
Hi, thanks I tried several driver versions and restarting and so on but it didn't really work. I decided to return the Tobii.

**Comment by theoractice** [comment]
@zloysmiertniy Do you see the red lights on the eye tracker? Can you calibrate it and see the bubble which indicates where you are looking at? 
I mean, is the eye tracker broken/not working at all or it only cannot work with OptiKey?

This is important because Tobii has decided to ban eye tracker 5 from working with aac softwares. If this also applies to OptiKey then it will be a big bad news for patients...
https://thinksmartbox.com/answer/tobii-discontinue-aac-software-compatibility-for-gaming-cameras/
https://www.facebook.com/groups/tobiidynavoxcommunity/permalink/4204563439576006

**Comment by AdamRoden** [comment]
@zloysmiertniy @theoractice 
I'm sorry I didn't engage sooner, but I can help if you want to try again.
I have been using the eye tracker 5 with Optikey since last summer. It works with Optikey but not Windows Eye Control or Tobii Computer Control. I'm not sure what all has been changed by Tobii, but I do know the new license terms of their software are meant to stifle anyone from offering software that interacts with their devices for anything other than gaming. (Yes, it applies to Optikey).
The goal of Optikey is to be device agnostic so any positional input device can be used. I'm very curious how their new batch of eye trackers is different.

**Comment by theoractice** [comment]
@AdamRoden @zloysmiertniy 
According to the release notes of their drivers, at least there will be a new batch of serial numbers:
https://help.tobii.com/hc/en-us/articles/360015813357
Click on version 1.53, you will see something like `Updated the Platform Runtime Service to support new serial numbers`.
However, To ban aac softwares only by detecting serial numbers, the detection must be done by the aac software itself, and OptiKey won't actually be affected in this way. Seems too good to be true.

**Comment by theoractice** [comment]
I can now confirm that OptiKey works with their new batch of eye trackers as usual. Fingers crossed.

**Comment by AdamRoden** [comment]
Good to hear. Speaking of compatibility, I can confirm that it also works with their new PCEye device. It is my preferred replacement for their Computer Control software.
