### ISSUE TITLE
Keyboards / plugins for coding

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#774]
I'm helping a user get set up with some keyboards for writing Java using Eclipse IDE.

@annakirkpatrick do you still use the BigHackerKeyboard in the repo or do you have anything more recent that you'd be happy to share?

@JuliusSweetland I remember some talk of plugins for IDE autocompletion but can't find the discussions. Did you implement something on the Optikey side to allow other processes to offer up suggestions or was it all just speculation?

If anyone else has any suggestions, please do share!

**Comment by JuliusSweetland** [comment]
Hi Kirsty. It was only ever a discussion. There was a proof of concept of
an http API that optikey would expose to be able to set suggestions
externally, but I don't remember it ever progressing.

**Comment by annakirkpatrick** [comment]
@kmcnaught Sorry for the delay in responding. I just started a new job in August, and I haven't kept up with all my email.

It is super exciting to hear other people are using Optikey for coding! I'm still using the original big hacker keyboard in the repository on my personal computer. At work, I'm actually using a variation of the big hacker keyboard layout that is vertical instead of horizontal. It's all about screen real estate and what aspect ratios work best for your particular IDE or other development tools. I've actually also added some of the mouse tools to my vertical layout. With the type of work that I'm doing now, I need the mouse more.

At work, I've also gotten a lot of benefit out of using a wider monitor. Even though the eye tracking quality degrades towards the edges of the monitor, I can still recover more usable screen space by using a vertical keyboard layout and just not placing any keys in the last couple of columns. But then the whole other half of the screen is available for other applications.

I think the exact set up that works best is going to be very individual to both the user and the task, and that experimentation will probably be required.

I'm happy to share my more recent layout. I'm not sure how to best do that since I can't upload XML here.  I could certainly add it to my fork when I get home.

Please feel free to reach out if I can help with anything else, or even if it would just be useful to get on a video chat and see a demo of how I use Optikey for code.

**Comment by kmcnaught** [comment]
@annakirkpatrick thanks! as you can tell I am also sporadic on github, no worries - I hope the new job is going well.

It looks like you can attach keyboards here by zipping them first - if you're happy to share I'd like to see. This is what we're currently working with (using Eclipse-specific shortcuts and no mouse actions since she uses Tobii controls for mouse actions).
[coding_eclipse.zip](https://github.com/OptiKey/OptiKey/files/7635671/coding_eclipse.zip)

Do you use the scratchpad / suggestions for coding or use autocomplete etc from your IDE? I was thinking of adding some functionality to load a temporary set of contextual vocabulary (e.g. java keywords, current variable names) to use with the "Simple" word prediction engine. Our needs are (I imagine) a bit different to yours as this user is learning coding for the first time but I'd love to hear your thoughts on workflow. A screen sharing session would be great too if you have time - you can find me via gmail as kirsty.mcnaught

**Comment by annakirkpatrick** [comment]
@kmcnaught The main keyboard I'm now using for code is BigHackerKeyboard_vertical_buffer_2.xml, included in this zip.
[CodeKeyboards.zip](https://github.com/OptiKey/OptiKey/files/7656488/CodeKeyboards.zip)

Note that it is intended for a wide monitor, which is why there are blank columns on the right-hand side. The eye tracking accuracy just degrades too much to be functional at the extreme edges of the monitor. On a more typical monitor, you could just delete those blank columns.

There are three "shortcut" keyboards that are accessed from the main keyboard. Two of them ("codeBits" and "ApiVars" ) are super specific to my work and not something I can share publicly. But suffice it to say that they are shortcuts for common code fragments and variable names. I did include the third ("chat") keyboard. It's not for coding. I use it with Microsoft teams at work. But it does give you the general idea for the type of layout that I used for the codeBits and APIVars keyboards.

Regarding scratchpad/suggestions, I have generally not included that on my coding keyboards. I work a lot in a terminal, and in this environment tab completion is unambiguously more useful, because it is contextual. I usually use vim as my text editor and so I don't really have completions/suggestions in that environment. What I use instead are the different sub keyboards with the common variables and code fragments. (And some of my code keys are pretty complex, laying down multi-line constructs. I actually designed them specifically to work in vim by using the vim navigation shortcuts. Though you could modify for any IDE of your choice.)

I do think it's an interesting idea to use the simple word prediction engine with a list of contextual suggestions. For me, I could even see using a static list similar to the content that already on those sub keyboards with shortcuts. It might be more efficient to use the prediction engine instead of navigating to the other keyboards. And of course would allow a larger list of "shortcuts." I might give that a try.

Most useful would definitely be contextual suggestions that could figure out currently active variable names and libraries. As well as keywords, etc. 

I'm not sure how the simple prediction engine handles spacing/delimiters. That might be an issue with object.method() calls for example. But you could probably get around this by allowing us custom set of delimiters, which for java would include white space characters as well as dot, comma (optional, depending on style) and probably the various brackets and braces, too. You would want to make those delimiters affect both the prediction engine and how the backspace word key works, I would think.

One other thought:
There has been some interesting work done on coding by voice that might be relevant here. I mention that mostly because they have also addressed issues around, for example, how to load a speech recognition engine with a set of currently valid variable names (which often are not English words). I honestly don't know how far that work has come. But I have been dipping my toes back into that world recently, so I will let you know if I come across anything interesting.
If you want to dig around, the dictation-toolbox group isn't a bad place to start: https://github.com/dictation-toolbox
In particular the caster and dragonfly repositories might have some interesting ideas that might translate.

I'll send you an email and we can find a time to talk. It's always good to exchange ideas.

**Comment by annakirkpatrick** [comment]
I should also mention that I gave a talk on using eye gaze for coding. The talk basically build things up piece by piece: eyetracker, OptiKey, custom keyboard, switches, editor.  It ends with a short demo.  It was recorded and is available online if you are interested: https://www.washington.edu/doit/webinars/?webinar=optikey

**Comment by kmcnaught** [comment]
Closing this, but it might be nice to consider showcasing different users' setups in the future.
