### ISSUE TITLE
Laggy behaviour when scrolling with gaze indicator

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#817]
If I turn on the gaze indicator and then use Look To Scroll, it quickly starts lagging behind. This video shows how it looks/feels. The Tobii Ghost bubbles correctly show my gaze, the Optikey reticle is getting left behind so scrolling ends up getting confused.

https://user-images.githubusercontent.com/12151404/159760867-27bddc42-e487-41b8-8632-2cfc3f1e8640.mp4

[edit: removed unrelated log]

**Comment by AdamRoden** [comment]
@kmcnaught Does that always happen? For me it all runs fine 99% of the time, but I have had times where Optikey on its own, or the Tobii stream overlay on its own will lag to a grinding halt.

On my machine, I get occasional overall lagginess with Optikey if Windows decides to throttle and prioritizes other processes above Optikey. This happens when my CPU gets hot or when battery optimization kicks in. For me it is unrelated to what I'm doing in Optikey. Do you have any ideas?

**Comment by kmcnaught** [comment]
Huh, from more experimentation today, I suspect that this is something that only happens in Debug mode. Which in some ways is fine, but I suspect points to the fact that both the gaze indicator and the scrolling are a bit heavier than they could be, which could impact users on older hardware. I'm going to close this specific issue as not immediately relevant, but open another to dump some performance related ideas into.
