### ISSUE TITLE
Mouse clicks not registering in games

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#875]
I often find that a game doesn't register the mouse click actions sent by OptiKey. As a workaround, I can quickly activate and deactivate the mouse drag action, but even that doesn't always work. For one game I had to do a macro that triggers the mouse drag method as fast as possible several times. Doing multiple clicks caused surprisingly few issues.

I know that simulated mouse clicks (or keyboard key presses) not registering by games is not an OptiKey-only issue. It happens with other accessibility software too -- also with on-screen keyboards. A developer told me once that it depends on how and at what level the game reads the mouse and keyboard inputs.

Anyway, how do you handle this issue when playing?

**Comment by AdamRoden** [comment]
1. Does it make a difference if you run the game in Windowed mode rather than Fullscreen? 
2. Some games ignore ultrafast keystrokes or clicks but work if you send key down, wait 20-50ms, then send key up.
3. For other ideas and suggestions check out the workarounds employed with AutoHotKey: https://www.autohotkey.com/board/topic/111737-how-to-make-ahk-work-in-most-games-the-basics/

**Comment by lsaranto** [comment]
@AdamRoden Thank you for the reply.
1. I always run games in window mode.
2. I have to test this.
3. Thanks for the link. Interesting info.

**Comment by kmcnaught** [comment]
@lsaranto I've been meaning to add `MouseLeftDown` and `MouseLeftUp` functionkeys so it's easier to control mouse clicks with delays. I suspect that in any case where a drag works, a longer "mouse down, pause then up" would also work. In those cases it usually means the game is polling the state of the mouse every however many milliseconds, rather than responding to mouse events. 

Have you tried https://github.com/kmcnaught/OKGO ? It's got various game specific features, and some QoL improvements - like for instance the ability to do `<KeyPress Duration="200">Space</KeyPress>` instead of needing all of `KeyDown, Wait, KeyUp`

Also controller support in various ways. 

Feel free to reach out at kirsty.mcnaught@gmail.com
